// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import React, { useState, useEffect, useRef, useMemo } from 'react';
import {
  AppLayout,
  ContentLayout,
  Header,
  SpaceBetween,
  Button,
  Form,
  FormField,
  Input,
  Textarea,
  Select,
  Container,
  Grid,
  Cards,
  Box,
  Alert,
  Modal,
  Badge,
  BreadcrumbGroup,
  RadioGroup,
  Wizard,
  PropertyFilter,
  CollectionPreferences,
  Checkbox,
  Tabs,
  Table,
  Link
} from '@cloudscape-design/components';
import Navigation from '../components/Navigation';
import { apiCall } from '../utils/api';
import { getAuthToken } from '../utils/auth';
import { useNavigate } from 'react-router-dom';

interface SoftwareComponent {
  softwareId: string;
  name: string;
  versionNumber: string;
  category: string;
  description: string;
  componentArn: string;
  estimatedInstallTime: string;
  diskSpaceRequired: string;
  gpuRequired?: boolean;
  platform?: string;
  parameters?: { name: string; description?: string; required?: boolean }[];
}

interface PipelineComponent {
  type: 'SOFTWARE_LIBRARY' | 'CUSTOM_SCRIPT';
  name: string;
  componentArn?: string;
  script?: string;
  parameterValues?: { [paramName: string]: string };
}

interface BaseImage {
  id: string;
  name: string;
  platform: string;
  description?: string;
  createdAt?: string;
  isAutoGenerated?: boolean;
}

// Base image options with platform info (for Windows and Linux)
const BASE_IMAGE_OPTIONS: BaseImage[] = [
  { id: 'windows-2025', name: 'Windows Server 2025 Base', platform: 'Windows', description: 'Latest Windows Server', isAutoGenerated: true },
  { id: 'windows-2022', name: 'Windows Server 2022 Base', platform: 'Windows', description: 'Windows Server', isAutoGenerated: true },
  { id: 'windows-2019', name: 'Windows Server 2019 Base', platform: 'Windows', description: 'Windows Server', isAutoGenerated: true },
  { id: 'ubuntu-22.04', name: 'Ubuntu Server 22.04 LTS', platform: 'Linux', description: 'Ubuntu/Debian-based', isAutoGenerated: true },
  { id: 'rocky-8', name: 'Rocky Linux 8', platform: 'Linux', description: 'RHEL-compatible, required for DaVinci Resolve', isAutoGenerated: true },
  { id: 'rocky-9', name: 'Rocky Linux 9', platform: 'Linux', description: 'RHEL-compatible, latest Rocky Linux', isAutoGenerated: true }
];

const ImageCreation: React.FC<{ config?: any }> = ({ config }) => {
  const navigate = useNavigate();
  const [pipelineName, setPipelineName] = useState('');
  const [description, setDescription] = useState('');
  const [baseImageId, setBaseImageId] = useState('windows-2025');
  const [instanceType, setInstanceType] = useState('m5.large');
  const [selectedComponents, setSelectedComponents] = useState<PipelineComponent[]>([]);
  const [softwareLibrary, setSoftwareLibrary] = useState<SoftwareComponent[]>([]);
  const [showCustomScriptModal, setShowCustomScriptModal] = useState(false);
  const [showAddSoftwareModal, setShowAddSoftwareModal] = useState(false);
  const [customScript, setCustomScript] = useState('');
  const [scriptName, setScriptName] = useState('');
  const [loadingSoftware, setLoadingSoftware] = useState(false);
  
  // Base image selection state
  const [activePlatformTab, setActivePlatformTab] = useState('windows');
  const [macosImages, setMacosImages] = useState<BaseImage[]>([]);
  const [loadingMacosImages, setLoadingMacosImages] = useState(false);
  const [selectedBaseImage, setSelectedBaseImage] = useState<BaseImage[]>([
    BASE_IMAGE_OPTIONS.find(img => img.id === 'windows-2025')!
  ]);
  
  // New software form state
  const [newSoftware, setNewSoftware] = useState({
    name: '',
    versionNumber: '',
    category: '',
    description: '',
    componentArn: '',
    script: '',
    sourceType: 'script',
    estimatedInstallTime: '',
    diskSpaceRequired: '',
    gpuRequired: false
  });
  const [creating, setCreating] = useState(false);
  const [selectedSoftwareIds, setSelectedSoftwareIds] = useState<string[]>([]);
  const selectedSoftwareIdsRef = useRef<string[]>([]);
  // Parameter values keyed by softwareId, then paramName
  const [componentParameterValues, setComponentParameterValues] = useState<{ [softwareId: string]: { [paramName: string]: string } }>({});
  const [error, setError] = useState('');
  const [activeStepIndex, setActiveStepIndex] = useState(0);
  const [filteringQuery, setFilteringQuery] = useState({ tokens: [], operation: 'and' });
  const [preferences, setPreferences] = useState({
    pageSize: 10,
    visibleContent: ['name', 'category', 'description', 'details']
  });

  // Load software library and macOS images on component mount
  useEffect(() => {
    loadSoftwareLibrary();
    loadMacosImages();
  }, []);

  // Load macOS images from the Images API
  const loadMacosImages = async () => {
    setLoadingMacosImages(true);
    try {
      const token = getAuthToken();
      if (!token) return;

      const response = await apiCall('/images', {
        method: 'GET',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        }
      });

      if (response.ok) {
        const data = await response.json();
        // Filter for macOS images only
        const macosOnly = (data || [])
          .filter((img: any) => img.platform?.toLowerCase() === 'macos')
          .map((img: any) => ({
            id: img.amiId,
            name: img.name,
            platform: 'macOS',
            description: img.description,
            createdAt: img.createdAt,
            isAutoGenerated: false
          }));
        setMacosImages(macosOnly);
      }
    } catch (error) {
      console.error('Failed to load macOS images:', error);
    } finally {
      setLoadingMacosImages(false);
    }
  };

  // Derive platform from selected base image
  const selectedPlatform = useMemo(() => {
    if (selectedBaseImage.length > 0) {
      return selectedBaseImage[0].platform;
    }
    return 'Windows';
  }, [selectedBaseImage]);

  // Auto-select instance type based on platform and selected software
  const selectedInstanceType = React.useMemo(() => {
    // macOS requires mac2.metal (dedicated host)
    if (selectedPlatform === 'macOS') {
      return 'mac2.metal';
    }
    const hasGpuSoftware = selectedComponents.some(comp => 
      comp.type === 'SOFTWARE_LIBRARY' && 
      softwareLibrary.find(sw => sw.componentArn === comp.componentArn)?.gpuRequired === true
    );
    return hasGpuSoftware ? 'g4dn.xlarge' : 'm5.large';
  }, [selectedComponents, softwareLibrary, selectedPlatform]);

  const baseImageName = useMemo(() => {
    if (selectedBaseImage.length > 0) {
      return selectedBaseImage[0].name;
    }
    return baseImageId;
  }, [selectedBaseImage, baseImageId]);

  // Update baseImageId when selection changes
  useEffect(() => {
    if (selectedBaseImage.length > 0) {
      setBaseImageId(selectedBaseImage[0].id);
    }
  }, [selectedBaseImage]);

  const filteredSoftware = React.useMemo(() => {
    if (!Array.isArray(softwareLibrary)) {
      return [];
    }
    
    let filtered = [...softwareLibrary];
    
    // Filter by platform - only show software matching the selected base image platform
    filtered = filtered.filter(software => {
      const softwarePlatform = software.platform || 'Windows'; // Default to Windows for backward compatibility
      return softwarePlatform === selectedPlatform;
    });

    // Apply PropertyFilter
    if (filteringQuery.tokens.length > 0) {
      filtered = filtered.filter(software => {
        return filteringQuery.tokens.every(token => {
          const { propertyKey, operator, value } = token;
          let itemValue = software[propertyKey as keyof SoftwareComponent];
          
          if (typeof itemValue === 'string') {
            itemValue = itemValue.toLowerCase();
          }
          const filterValue = value.toLowerCase();

          switch (operator) {
            case ':':
              return itemValue.includes(filterValue);
            case '!:':
              return !itemValue.includes(filterValue);
            case '=':
              return itemValue === filterValue;
            case '!=':
              return itemValue !== filterValue;
            default:
              return true;
          }
        });
      });
    }

    return filtered;
  }, [softwareLibrary, filteringQuery, selectedPlatform]);

  const loadSoftwareLibrary = async () => {
    setLoadingSoftware(true);
    try {
      const token = getAuthToken();
      if (!token) return;

      const response = await apiCall('/images/software', {
        method: 'GET',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        }
      });

      if (response.ok) {
        const data = await response.json();
        setSoftwareLibrary(data.items || []);
      }
    } catch (error) {
      console.error('Failed to load software library:', error);
    } finally {
      setLoadingSoftware(false);
    }
  };

  const addSoftwareToLibrary = async () => {
    // Validate required fields
    if (!newSoftware.name) {
      setError('Software name is required');
      return;
    }
    
    if (newSoftware.sourceType === 'arn' && !newSoftware.componentArn) {
      setError('Component ARN is required when using existing component');
      return;
    }
    
    if (newSoftware.sourceType === 'script' && !newSoftware.script) {
      setError('Custom script is required when uploading script');
      return;
    }

    try {
      const token = getAuthToken();
      if (!token) return;

      // Remove componentArn if using script mode (Lambda will generate it)
      const payload = { ...newSoftware };
      if (newSoftware.sourceType === 'script') {
        delete payload.componentArn;
      }

      const response = await apiCall('/images/software', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(payload)
      });

      if (response.ok) {
        setShowAddSoftwareModal(false);
        setNewSoftware({
          name: '',
          versionNumber: '',
          category: '',
          description: '',
          componentArn: '',
          script: '',
          sourceType: 'script',
          estimatedInstallTime: '',
          diskSpaceRequired: '',
          gpuRequired: false
        });
        loadSoftwareLibrary(); // Reload the library
      } else {
        setError('Failed to add software to library');
      }
    } catch (error) {
      console.error('Failed to add software:', error);
      setError('Failed to add software to library');
    }
  };

  const addSoftwareComponent = (software: SoftwareComponent) => {
    setSelectedComponents(prev => {
      // Check if component already exists
      const exists = prev.some(comp => 
        comp.type === 'SOFTWARE_LIBRARY' && comp.componentArn === software.componentArn
      );
      
      if (exists) return prev;
      
      const component: PipelineComponent = {
        type: 'SOFTWARE_LIBRARY',
        name: `${software.name}${software.versionNumber ? ` v${software.versionNumber}` : ''}`,
        componentArn: software.componentArn
      };
      return [...prev, component];
    });
  };

  const addCustomScript = () => {
    if (scriptName && customScript) {
      // Check if script with same name already exists
      const exists = selectedComponents.some(comp => 
        comp.type === 'CUSTOM_SCRIPT' && comp.name === scriptName
      );
      
      if (exists) return;
      
      const component: PipelineComponent = {
        type: 'CUSTOM_SCRIPT',
        name: scriptName,
        script: customScript
      };
      setSelectedComponents([...selectedComponents, component]);
      setShowCustomScriptModal(false);
      setScriptName('');
      setCustomScript('');
    }
  };

  const removeComponent = (index: number) => {
    const newComponents = [...selectedComponents];
    newComponents.splice(index, 1);
    setSelectedComponents(newComponents);
  };

  const createPipeline = async () => {
    if (!pipelineName || selectedBaseImage.length === 0) {
      setError('Pipeline name and base image are required');
      return;
    }

    setCreating(true);
    setError('');
    
    try {
      const token = getAuthToken();
      if (!token) {
        setError('Authentication required');
        return;
      }

      const response = await apiCall('/images/create-pipeline', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`,
        },
        body: JSON.stringify({
          name: pipelineName,
          description,
          baseImageId,
          platform: selectedPlatform,
          instanceType: selectedInstanceType,
          components: selectedComponents
        })
      });

      if (response.ok) {
        navigate('/images');
      } else {
        const errorData = await response.json();
        setError(errorData.error || 'Failed to create pipeline');
      }
    } catch (error) {
      console.error('Error creating pipeline:', error);
      setError('Failed to create pipeline');
    } finally {
      setCreating(false);
    }
  };

  return (
    <AppLayout
      navigation={<Navigation isAdmin={true} productName={config?.productName} acronym={config?.acronym} />}
      disableContentPaddings={true}
      toolsHide={true}
      content={
        <ContentLayout
          defaultPadding
          headerVariant="high-contrast"
          maxContentWidth={1200}
          breadcrumbs={
            <BreadcrumbGroup
              items={[
                { text: 'Dashboard', href: '/dashboard' },
                { text: 'Images', href: '/images' },
                { text: 'Create Pipeline' }
              ]}
              ariaLabel="Breadcrumbs"
            />
          }
          header={
            <Box padding={{ vertical: "l" }}>
              <Grid
                gridDefinition={[
                  { colspan: { default: 12, xs: 8, s: 9 } },
                  { colspan: { default: 12, xs: 4, s: 3 } }
                ]}
              >
                <div>
                  <Box variant="h1" fontSize="display-l">
                    Create Image Pipeline
                  </Box>
                  <Box
                    variant="p"
                    color="text-body-secondary"
                    margin={{ top: "xxs", bottom: "s" }}
                  >
                    Create custom AMIs using EC2 Image Builder. Configure your base image, add software components, and define build settings.
                  </Box>
                </div>
              </Grid>
            </Box>
          }
        >
          {error && (
            <Alert type="error" dismissible onDismiss={() => setError('')}>
              {error}
            </Alert>
          )}

          <Container>
            <Wizard
              i18nStrings={{
                stepNumberLabel: stepNumber => `Step ${stepNumber}`,
                collapsedStepsLabel: (stepNumber, stepsCount) => `Step ${stepNumber} of ${stepsCount}`,
                skipToButtonLabel: (step, stepNumber) => `Skip to ${step.title}`,
                navigationAriaLabel: "Steps",
                cancelButton: "Cancel",
                previousButton: "Previous",
                nextButton: "Next",
                submitButton: "Create Pipeline",
                optional: "optional"
              }}
              onNavigate={({ detail }) => {
                // Sync software selections when moving forward from step 2
                if (detail.requestedStepIndex > activeStepIndex && activeStepIndex === 1) {
                  const currentSelections = selectedSoftwareIdsRef.current;
                  
                  // Get selected ARNs
                  const selectedArns = new Set(
                    currentSelections
                      .map(id => softwareLibrary.find(item => item.softwareId === id)?.componentArn)
                      .filter(Boolean)
                  );
                  
                  // Remove all software library components and re-add only selected ones
                  setSelectedComponents(prev => {
                    const nonSoftware = prev.filter(comp => comp.type !== 'SOFTWARE_LIBRARY');
                    const selectedSoftware = currentSelections
                      .map(id => softwareLibrary.find(item => item.softwareId === id))
                      .filter(Boolean)
                      .map(software => ({
                        type: 'SOFTWARE_LIBRARY' as const,
                        name: `${software.name}${software.versionNumber ? ` v${software.versionNumber}` : ''}`,
                        componentArn: software.componentArn,
                        parameterValues: componentParameterValues[software.softwareId] || undefined
                      }));
                    return [...nonSoftware, ...selectedSoftware];
                  });
                }
                
                // Sync selectedSoftwareIds when navigating back to step 2
                if (detail.requestedStepIndex === 1) {
                  const softwareComponents = selectedComponents.filter(comp => comp.type === 'SOFTWARE_LIBRARY');
                  const ids = softwareComponents
                    .map(comp => softwareLibrary.find(item => item.componentArn === comp.componentArn)?.softwareId)
                    .filter(Boolean) as string[];
                  setSelectedSoftwareIds(ids);
                  selectedSoftwareIdsRef.current = ids;
                }
                
                setActiveStepIndex(detail.requestedStepIndex);
              }}
              activeStepIndex={activeStepIndex}
              onCancel={() => navigate('/images')}
              onSubmit={createPipeline}
              isLoadingNextStep={creating}
              steps={[
                {
                  title: "Pipeline Configuration",
                  content: (
                    <SpaceBetween direction="vertical" size="m">
                      <FormField label="Pipeline Name" constraintText="Enter a descriptive name">
                        <Input
                          value={pipelineName}
                          onChange={({ detail }) => setPipelineName(detail.value)}
                          placeholder="e.g., Media Workstation Pipeline"
                        />
                      </FormField>
                      <FormField label="Description" constraintText="Optional description">
                        <Textarea
                          value={description}
                          onChange={({ detail }) => setDescription(detail.value)}
                          placeholder="Describe what this image will be used for..."
                          rows={3}
                        />
                      </FormField>
                      <FormField label="Base Image" description="Select the operating system for your image pipeline">
                        <Tabs
                          activeTabId={activePlatformTab}
                          onChange={({ detail }) => {
                            setActivePlatformTab(detail.activeTabId);
                            // Clear selection when switching tabs
                            setSelectedBaseImage([]);
                          }}
                          tabs={[
                            {
                              id: 'windows',
                              label: 'Windows',
                              content: (
                                <Table
                                  columnDefinitions={[
                                    { id: 'name', header: 'Name', cell: (item: BaseImage) => item.name },
                                    { id: 'description', header: 'Description', cell: (item: BaseImage) => item.description || '-' }
                                  ]}
                                  items={BASE_IMAGE_OPTIONS.filter(img => img.platform === 'Windows')}
                                  selectionType="single"
                                  selectedItems={selectedBaseImage.filter(img => img.platform === 'Windows')}
                                  onSelectionChange={({ detail }) => {
                                    setSelectedBaseImage(detail.selectedItems as BaseImage[]);
                                    // Clear software when platform changes
                                    if (selectedPlatform !== 'Windows') {
                                      setSelectedSoftwareIds([]);
                                      selectedSoftwareIdsRef.current = [];
                                      setSelectedComponents(prev => prev.filter(c => c.type !== 'SOFTWARE_LIBRARY'));
                                    }
                                  }}
                                  trackBy="id"
                                  variant="embedded"
                                  empty={<Box textAlign="center">No Windows base images available</Box>}
                                />
                              )
                            },
                            {
                              id: 'linux',
                              label: 'Linux',
                              content: (
                                <Table
                                  columnDefinitions={[
                                    { id: 'name', header: 'Name', cell: (item: BaseImage) => item.name },
                                    { id: 'description', header: 'Description', cell: (item: BaseImage) => item.description || '-' }
                                  ]}
                                  items={BASE_IMAGE_OPTIONS.filter(img => img.platform === 'Linux')}
                                  selectionType="single"
                                  selectedItems={selectedBaseImage.filter(img => img.platform === 'Linux')}
                                  onSelectionChange={({ detail }) => {
                                    setSelectedBaseImage(detail.selectedItems as BaseImage[]);
                                    // Clear software when platform changes
                                    if (selectedPlatform !== 'Linux') {
                                      setSelectedSoftwareIds([]);
                                      selectedSoftwareIdsRef.current = [];
                                      setSelectedComponents(prev => prev.filter(c => c.type !== 'SOFTWARE_LIBRARY'));
                                    }
                                  }}
                                  trackBy="id"
                                  variant="embedded"
                                  empty={<Box textAlign="center">No Linux base images available</Box>}
                                />
                              )
                            },
                            {
                              id: 'macos',
                              label: 'macOS',
                              content: (
                                <SpaceBetween direction="vertical" size="s">
                                  {macosImages.length === 0 && !loadingMacosImages && (
                                    <Alert type="info">
                                      No macOS base images available. macOS pipelines require a DCV-Ready base image. Go to <Link href="/images">Image Management</Link> and build one of the system pipelines (macOS Sequoia or Sonoma) first.
                                    </Alert>
                                  )}
                                  <Table
                                    columnDefinitions={[
                                      { id: 'name', header: 'Name', cell: (item: BaseImage) => item.name },
                                      { id: 'createdAt', header: 'Created', cell: (item: BaseImage) => item.createdAt ? new Date(item.createdAt).toLocaleDateString() : '-' }
                                    ]}
                                    items={macosImages}
                                    loading={loadingMacosImages}
                                    loadingText="Loading macOS images..."
                                    selectionType="single"
                                    selectedItems={selectedBaseImage.filter(img => img.platform === 'macOS')}
                                    onSelectionChange={({ detail }) => {
                                      setSelectedBaseImage(detail.selectedItems as BaseImage[]);
                                      // Clear software when platform changes
                                      if (selectedPlatform !== 'macOS') {
                                        setSelectedSoftwareIds([]);
                                        selectedSoftwareIdsRef.current = [];
                                        setSelectedComponents(prev => prev.filter(c => c.type !== 'SOFTWARE_LIBRARY'));
                                      }
                                    }}
                                    trackBy="id"
                                    variant="embedded"
                                    empty={<Box textAlign="center">No macOS base images available</Box>}
                                  />
                                </SpaceBetween>
                              )
                            }
                          ]}
                        />
                      </FormField>
                    </SpaceBetween>
                  )
                },
                {
                  title: "Software Components",
                  content: (
                    <SpaceBetween direction="vertical" size="m">
                      <Alert type="info">
                        Showing {selectedPlatform} software components only. To see {selectedPlatform === 'Windows' ? 'Linux' : 'Windows'} software, change the base image in the previous step.
                      </Alert>
                      <Grid gridDefinition={[{ colspan: 6 }, { colspan: 6 }]}>
                        <Box variant="h3">Available Software ({filteredSoftware.length})</Box>
                        <Box float="right">
                          <SpaceBetween direction="horizontal" size="xs">
                            <Button
                              iconName="refresh"
                              onClick={loadSoftwareLibrary}
                              loading={loadingSoftware}
                            />
                            <Button
                              onClick={() => navigate('/software')}
                            >
                              Manage Library
                            </Button>
                            <Button
                              variant="primary"
                              onClick={() => setShowAddSoftwareModal(true)}
                            >
                              Add Software
                            </Button>
                          </SpaceBetween>
                        </Box>
                      </Grid>
                      
                      <Grid gridDefinition={[{ colspan: 12 }]}>
                        <PropertyFilter
                          query={filteringQuery}
                          onChange={({ detail }) => setFilteringQuery(detail)}
                          filteringProperties={[
                            {
                              key: 'name',
                              operators: [':', '!:', '=', '!='],
                              propertyLabel: 'Name',
                              groupValuesLabel: 'Name values'
                            },
                            {
                              key: 'category',
                              operators: [':', '!:', '=', '!='],
                              propertyLabel: 'Category',
                              groupValuesLabel: 'Category values'
                            }
                          ]}
                          filteringOptions={[
                            ...softwareLibrary.map(item => ({ propertyKey: 'name', value: item.name })),
                            ...Array.from(new Set(softwareLibrary.map(item => item.category))).map(category => ({ propertyKey: 'category', value: category }))
                          ].filter((option, index, self) => 
                            index === self.findIndex(o => o.propertyKey === option.propertyKey && o.value === option.value)
                          )}
                          placeholder="Search software"
                          filteringPlaceholder="Filter software"
                          filteringAriaLabel="Filter software"
                          i18nStrings={{
                            filteringAriaLabel: "Filter software",
                            dismissAriaLabel: "Dismiss",
                            filteringPlaceholder: "Filter software",
                            groupValuesText: "Values",
                            groupPropertiesText: "Properties",
                            operatorsText: "Operators",
                            operationAndText: "and",
                            operationOrText: "or",
                            operatorLessText: "Less than",
                            operatorLessOrEqualText: "Less than or equal",
                            operatorGreaterText: "Greater than",
                            operatorGreaterOrEqualText: "Greater than or equal",
                            operatorContainsText: "Contains",
                            operatorDoesNotContainText: "Does not contain",
                            operatorEqualsText: "Equals",
                            operatorDoesNotEqualText: "Does not equal",
                            editTokenText: "Edit filter",
                            propertyText: "Property",
                            operatorText: "Operator",
                            valueText: "Value",
                            cancelActionText: "Cancel",
                            applyActionText: "Apply",
                            allPropertiesLabel: "All properties",
                            tokenLimitShowMore: "Show more",
                            tokenLimitShowFewer: "Show fewer",
                            clearFiltersText: "Clear filters",
                            removeTokenButtonAriaLabel: (token) => `Remove token ${token.propertyKey} ${token.operator} ${token.value}`,
                            enteredTextLabel: (text) => `Use: "${text}"`
                          }}
                          expandToViewport={true}
                        />
                      </Grid>
                      
                      <Cards
                        loading={loadingSoftware}
                        loadingText="Loading software library..."
                        selectionType="multi"
                        entireCardClickable
                        trackBy="softwareId"
                        ariaLabels={{
                          itemSelectionLabel: (e, item) => `select ${item.name}`,
                          selectionGroupLabel: "Software selection"
                        }}
                        selectedItems={filteredSoftware.filter(item => selectedSoftwareIds.includes(item.softwareId))}
                        onSelectionChange={({ detail }) => {
                          const ids = detail.selectedItems.map(item => item.softwareId);
                          setSelectedSoftwareIds(ids);
                          selectedSoftwareIdsRef.current = ids;
                        }}
                        empty={
                          <Box textAlign="center" color="inherit">
                            <b>No software components available</b>
                            <Box variant="p" color="inherit">
                              Add software components to your library to get started.
                            </Box>
                          </Box>
                        }
                        cardDefinition={{
                          header: item => (
                            <SpaceBetween direction="horizontal" size="s">
                              <Box variant="strong">{item.name} {item.versionNumber && `v${item.versionNumber}`}</Box>
                              <Badge color="blue">{item.category}</Badge>
                            </SpaceBetween>
                          ),
                          sections: [
                            {
                              id: 'description',
                              content: item => item.description
                            },
                            {
                              id: 'details',
                              content: item => (
                                <SpaceBetween direction="vertical" size="xs">
                                  <Box variant="small">Install Time: {item.estimatedInstallTime}</Box>
                                  <Box variant="small">Disk Space: {item.diskSpaceRequired}</Box>
                                </SpaceBetween>
                              )
                            }
                          ]
                        }}
                        cardsPerRow={[{ cards: 1 }, { minWidth: 500, cards: 2 }]}
                        items={filteredSoftware}
                      />

                      {/* Parameter inputs for selected components */}
                      {selectedSoftwareIds.length > 0 && (() => {
                        const selectedWithParams = selectedSoftwareIds
                          .map(id => softwareLibrary.find(item => item.softwareId === id))
                          .filter(sw => sw && sw.parameters && sw.parameters.length > 0);
                        if (selectedWithParams.length === 0) return null;
                        return (
                          <Container header={<Header variant="h3">Component Parameters</Header>}>
                            <SpaceBetween direction="vertical" size="m">
                              {selectedWithParams.map(software => (
                                <SpaceBetween key={software!.softwareId} direction="vertical" size="s">
                                  <Box variant="h4">{software!.name}</Box>
                                  {software!.parameters!.map(param => (
                                    <FormField
                                      key={param.name}
                                      label={
                                        <span>
                                          {param.name}
                                          {param.required && <span style={{ color: 'red' }}> *</span>}
                                        </span>
                                      }
                                      description={param.description}
                                    >
                                      <Input
                                        value={componentParameterValues[software!.softwareId]?.[param.name] || ''}
                                        onChange={({ detail }) => {
                                          setComponentParameterValues(prev => ({
                                            ...prev,
                                            [software!.softwareId]: {
                                              ...prev[software!.softwareId],
                                              [param.name]: detail.value
                                            }
                                          }));
                                        }}
                                        placeholder={`Enter ${param.name}`}
                                      />
                                    </FormField>
                                  ))}
                                </SpaceBetween>
                              ))}
                            </SpaceBetween>
                          </Container>
                        );
                      })()}
                    </SpaceBetween>
                  )
                },
                {
                  title: "Custom Scripts",
                  content: (
                    <Container header={<Header variant="h2">Add Custom Installation Scripts</Header>}>
                      <SpaceBetween direction="vertical" size="m">
                        <Box float="right">
                          <Button variant="primary" onClick={() => setShowCustomScriptModal(true)}>
                            Add Custom Script
                          </Button>
                        </Box>
                        {selectedComponents.filter(comp => comp.type === 'CUSTOM_SCRIPT').length === 0 ? (
                          <Box textAlign="center" color="inherit">
                            <b>No custom scripts added</b>
                            <Box variant="p" color="inherit">
                              Add custom {selectedPlatform === 'Linux' ? 'Bash' : 'PowerShell'} scripts for specialized installation tasks.
                            </Box>
                          </Box>
                        ) : (
                          <SpaceBetween direction="vertical" size="s">
                            {selectedComponents.filter(comp => comp.type === 'CUSTOM_SCRIPT').map((component, index) => (
                              <Box key={index} padding="s">
                                <SpaceBetween direction="horizontal" size="s">
                                  <Box variant="strong">{component.name}</Box>
                                  <Badge color="blue">CUSTOM_SCRIPT</Badge>
                                  <Button
                                    variant="link"
                                    onClick={() => removeComponent(selectedComponents.indexOf(component))}
                                  >
                                    Remove
                                  </Button>
                                </SpaceBetween>
                              </Box>
                            ))}
                          </SpaceBetween>
                        )}
                      </SpaceBetween>
                    </Container>
                  )
                },
                {
                  title: "Review",
                  content: (
                    <SpaceBetween direction="vertical" size="l">
                      <Container header={<Header variant="h2">Pipeline Configuration</Header>}>
                        <SpaceBetween direction="vertical" size="s">
                          <Box><strong>Name:</strong> {pipelineName}</Box>
                          <Box><strong>Description:</strong> {description || 'None'}</Box>
                          <Box><strong>Base Image:</strong> {baseImageName}</Box>
                          <Box><strong>Platform:</strong> {selectedPlatform}</Box>
                          <Box><strong>Instance Type:</strong> {selectedInstanceType} {selectedInstanceType === 'mac2.metal' ? '(macOS Dedicated Host)' : selectedInstanceType === 'g4dn.xlarge' ? '(GPU - Auto-selected for media software)' : '(Standard)'}</Box>
                        </SpaceBetween>
                      </Container>
                      
                      <Container header={<Header variant="h2">Selected Components ({selectedComponents.length})</Header>}>
                        {selectedComponents.length === 0 ? (
                          <Box textAlign="center" color="inherit">
                            <b>No components selected</b>
                          </Box>
                        ) : (
                          <SpaceBetween direction="vertical" size="s">
                            {selectedComponents.map((component, index) => (
                              <Box key={index} padding="s">
                                <SpaceBetween direction="horizontal" size="s">
                                  <Box variant="strong">{component.name}</Box>
                                  <Badge color={component.type === 'CUSTOM_SCRIPT' ? 'blue' : 'green'}>
                                    {component.type}
                                  </Badge>
                                </SpaceBetween>
                              </Box>
                            ))}
                          </SpaceBetween>
                        )}
                      </Container>
                    </SpaceBetween>
                  )
                }
              ]}
            />
          </Container>

          <Modal
            visible={showCustomScriptModal}
            onDismiss={() => setShowCustomScriptModal(false)}
            header="Add Custom Script"
            footer={
              <Box float="right">
                <SpaceBetween direction="horizontal" size="s">
                  <Button variant="link" onClick={() => setShowCustomScriptModal(false)}>
                    Cancel
                  </Button>
                  <Button variant="primary" onClick={addCustomScript}>
                    Add Script
                  </Button>
                </SpaceBetween>
              </Box>
            }
          >
            <SpaceBetween direction="vertical" size="m">
              <FormField label="Script Name">
                <Input
                  value={scriptName}
                  onChange={({ detail }) => setScriptName(detail.value)}
                  placeholder="e.g., Configure System Settings"
                />
              </FormField>
              <FormField label={selectedPlatform === 'Linux' ? 'Bash Script' : 'PowerShell Script'}>
                <Textarea
                  value={customScript}
                  onChange={({ detail }) => setCustomScript(detail.value)}
                  placeholder={selectedPlatform === 'Linux' 
                    ? '#!/bin/bash\n# Enter your Bash script here...'
                    : '# Enter your PowerShell script here...'}
                  rows={10}
                />
              </FormField>
            </SpaceBetween>
          </Modal>

          <Modal
            visible={showAddSoftwareModal}
            onDismiss={() => setShowAddSoftwareModal(false)}
            header="Add Software to Library"
            footer={
              <Box float="right">
                <SpaceBetween direction="horizontal" size="s">
                  <Button variant="link" onClick={() => setShowAddSoftwareModal(false)}>
                    Cancel
                  </Button>
                  <Button variant="primary" onClick={addSoftwareToLibrary}>
                    Add Software
                  </Button>
                </SpaceBetween>
              </Box>
            }
          >
            <SpaceBetween direction="vertical" size="m">
              <Grid gridDefinition={[{ colspan: 8 }, { colspan: 4 }]}>
                <FormField label="Software Name" constraintText="Required">
                  <Input
                    value={newSoftware.name}
                    onChange={({ detail }) => setNewSoftware({...newSoftware, name: detail.value})}
                    placeholder="e.g., Adobe Creative Suite"
                  />
                </FormField>
                <FormField label="Version Number" constraintText="Optional - leave empty for latest version">
                  <Input
                    value={newSoftware.versionNumber}
                    onChange={({ detail }) => setNewSoftware({...newSoftware, versionNumber: detail.value})}
                    placeholder="e.g., 2024 or leave empty for latest"
                  />
                </FormField>
              </Grid>
              <FormField label="Category" constraintText="Select software category">
                <Select
                  selectedOption={newSoftware.category ? { label: newSoftware.category, value: newSoftware.category } : null}
                  onChange={({ detail }) => setNewSoftware({...newSoftware, category: detail.selectedOption.value!})}
                  options={[
                    { label: 'Development', value: 'development' },
                    { label: 'Media', value: 'media' },
                    { label: 'System', value: 'system' },
                    { label: 'Utilities', value: 'utilities' }
                  ]}
                  placeholder="Choose a category"
                />
              </FormField>
              <FormField label="Description">
                <Textarea
                  value={newSoftware.description}
                  onChange={({ detail }) => setNewSoftware({...newSoftware, description: detail.value})}
                  placeholder="Brief description of the software..."
                  rows={3}
                />
              </FormField>
              <FormField label="Component Source" constraintText="Required - Choose existing ARN or upload script">
                <RadioGroup
                  value={newSoftware.sourceType || 'script'}
                  onChange={({ detail }) => setNewSoftware({...newSoftware, sourceType: detail.value})}
                  items={[
                    { value: 'script', label: 'Upload Custom Script' },
                    { value: 'arn', label: 'Existing Component ARN' }
                  ]}
                />
              </FormField>
              
              {(newSoftware.sourceType || 'script') === 'arn' ? (
                <FormField label="Component ARN" constraintText="Required">
                  <Input
                    value={newSoftware.componentArn}
                    onChange={({ detail }) => setNewSoftware({...newSoftware, componentArn: detail.value})}
                    placeholder="arn:aws:imagebuilder:us-east-1:123456789012:component/..."
                  />
                </FormField>
              ) : (
                <FormField label="PowerShell Script" constraintText="Required">
                  <Textarea
                    value={newSoftware.script}
                    onChange={({ detail }) => setNewSoftware({...newSoftware, script: detail.value})}
                    placeholder="Enter your PowerShell script here..."
                    rows={8}
                  />
                </FormField>
              )}
              <Grid gridDefinition={[{ colspan: 6 }, { colspan: 6 }]}>
                <FormField label="Estimated Install Time">
                  <Input
                    value={newSoftware.estimatedInstallTime}
                    onChange={({ detail }) => setNewSoftware({...newSoftware, estimatedInstallTime: detail.value})}
                    placeholder="e.g., 30 minutes"
                  />
                </FormField>
                <FormField label="Disk Space Required">
                  <Input
                    value={newSoftware.diskSpaceRequired}
                    onChange={({ detail }) => setNewSoftware({...newSoftware, diskSpaceRequired: detail.value})}
                    placeholder="e.g., 8 GB"
                  />
                </FormField>
              </Grid>
              <Checkbox
                checked={newSoftware.gpuRequired}
                onChange={({ detail }) => setNewSoftware({...newSoftware, gpuRequired: detail.checked})}
              >
                Requires GPU (will use GPU-enabled build instance)
              </Checkbox>
            </SpaceBetween>
          </Modal>
        </ContentLayout>
      }
    />
  );
};

export default ImageCreation;
