// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import React, { useState, useEffect } from 'react';
import {
  AppLayout,
  ContentLayout,
  Header,
  SpaceBetween,
  Button,
  Table,
  Box,
  Modal,
  FormField,
  Input,
  Select,
  Textarea,
  Alert,
  Badge,
  TextFilter,
  PropertyFilter,
  CollectionPreferences,
  BreadcrumbGroup,
  Grid,
  StatusIndicator,
  Pagination,
  ExpandableSection,
  Link
} from '@cloudscape-design/components';
import Navigation from '../components/Navigation';
import { getAuthToken } from '../utils/auth';
import { apiCall } from '../utils/api';

interface AMIImage {
  amiId: string;
  name: string;
  platform: string;
  description?: string;
  owner?: string;
  state?: string;
  visibility?: string;
  architecture?: string;
  virtualizationType?: string;
  createdAt?: string;
  updatedAt?: string;
  isAutoGenerated?: boolean;
  requiresPipeline?: boolean; // Raw macOS AMIs need DCV-Ready pipeline processing
  requiresPipelineReason?: string;
  pipelineId?: string;
  region?: string;
  sourceRegion?: string;
}

// Grouped image for display - represents a pipeline output or standalone image
interface GroupedImage {
  id: string; // pipelineId or amiId for standalone
  name: string;
  platform: string;
  description?: string;
  state?: string;
  createdAt?: string;
  isAutoGenerated?: boolean;
  requiresPipeline?: boolean;
  pipelineId?: string;
  // Computed type for filtering: 'Base Image', 'Pipeline', or 'Imported'
  type: string;
  // For grouped images, this contains all regional AMIs
  regions: Array<{
    region: string;
    amiId: string;
  }>;
  // For standalone images (no pipelineId), this is the single AMI
  amiId?: string;
  region?: string;
}

interface ImagePipeline {
  pipelineId: string;
  name: string;
  description?: string;
  status: 'CREATED' | 'BUILDING' | 'COMPLETED' | 'FAILED';
  baseImageId: string;
  baseOsVersion?: string; // e.g., "Windows Server 2022", "Windows Server 2019", "Ubuntu 20.04"
  components: PipelineComponent[];
  createdAt: string;
  updatedAt: string;
  pipelineArn: string;
  isSystemPipeline?: boolean; // System pipelines cannot be deleted
}

interface PipelineComponent {
  name: string;
  componentArn: string;
  type?: string;
}

interface SoftwareComponent {
  componentId: string;
  name: string;
  componentArn: string;
  componentVersion?: string;
  versionNumber?: string;
}

const ImageManagement: React.FC<{ config?: any }> = ({ config }) => {
  console.log('ImageManagement: Component rendering');
  const [images, setImages] = useState<AMIImage[]>([]);
  const [pipelines, setPipelines] = useState<ImagePipeline[]>([]);
  const [loading, setLoading] = useState(true);
  const [pipelinesLoading, setPipelinesLoading] = useState(true);
  const [selectedItems, setSelectedItems] = useState<GroupedImage[]>([]);
  const [selectedPipelines, setSelectedPipelines] = useState<ImagePipeline[]>([]);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [showDeletePipelineModal, setShowDeletePipelineModal] = useState(false);
  const [showEditPipelineModal, setShowEditPipelineModal] = useState(false);
  const [editingPipeline, setEditingPipeline] = useState<ImagePipeline | null>(null);
  const [editPipelineComponents, setEditPipelineComponents] = useState<PipelineComponent[]>([]);
  const [softwareLibrary, setSoftwareLibrary] = useState<SoftwareComponent[]>([]);
  const [updatingPipeline, setUpdatingPipeline] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [building, setBuilding] = useState(false);
  const [editingImage, setEditingImage] = useState<AMIImage | null>(null);
  
  // Expandable rows state for multi-region images
  const [expandedItems, setExpandedItems] = useState<GroupedImage[]>([]);
  
  // Pipeline table state
  const [pipelineFilteringText, setPipelineFilteringText] = useState({ tokens: [], operation: 'and' });
  const [pipelineFilteringProperties, setPipelineFilteringProperties] = useState<any[]>([]);
  
  // Pagination state
  const [currentPageIndex, setCurrentPageIndex] = useState(1);
  const [pipelineCurrentPageIndex, setPipelineCurrentPageIndex] = useState(1);
  
  // Load pipeline preferences from localStorage or use defaults
  const getInitialPipelinePreferences = () => {
    try {
      const saved = localStorage.getItem('pipelines-table-preferences');
      if (saved) {
        const parsed = JSON.parse(saved);
        // Check if the saved preferences have the old baseImageId column
        const hasOldColumn = parsed.contentDisplay?.some(item => item.id === 'baseImageId');
        if (hasOldColumn) {
          // Reset to new defaults if old column structure is found
          localStorage.removeItem('pipelines-table-preferences');
          return getDefaultPipelinePreferences();
        }
        return parsed;
      }
    } catch (error) {
      console.warn('Failed to load pipeline preferences from localStorage:', error);
    }
    
    return getDefaultPipelinePreferences();
  };

  const getDefaultPipelinePreferences = () => ({
    pageSize: 10,
    contentDisplay: [
      { id: 'name', visible: true },
      { id: 'baseOsVersion', visible: true },
      { id: 'components', visible: true },
      { id: 'status', visible: true },
      { id: 'createdAt', visible: true }
    ],
    wrapLines: false
  });

  const [pipelinePreferences, setPipelinePreferences] = useState(getInitialPipelinePreferences);
  const [alert, setAlert] = useState<{ type: 'success' | 'error'; message: string } | null>(null);
  const [filteringText, setFilteringText] = useState('');
  const [typeFilter, setTypeFilter] = useState<any>(null);
  const [platformFilter, setPlatformFilter] = useState<any>(null);
  const [sortingColumn, setSortingColumn] = useState<any>({});
  const [pipelineSortingColumn, setPipelineSortingColumn] = useState<any>({});
  // Load preferences from localStorage or use defaults
  const getInitialPreferences = () => {
    try {
      const saved = localStorage.getItem('images-table-preferences');
      if (saved) {
        return JSON.parse(saved);
      }
    } catch (error) {
      console.warn('Failed to load preferences from localStorage:', error);
    }
    
    return {
      pageSize: 10,
      wrapLines: false,
      stripedRows: false,
      contentDensity: 'comfortable',
      contentDisplay: [
        { id: 'name', visible: true },
        { id: 'platform', visible: true },
        { id: 'state', visible: true },
        { id: 'regions', visible: true },
        { id: 'type', visible: true },
        { id: 'createdAt', visible: true }
      ],
      stickyColumns: { first: 0, last: 0 }
    };
  };

  const [preferences, setPreferences] = useState(getInitialPreferences);

  // Save preferences to localStorage whenever they change
  const updatePreferences = (newPreferences) => {
    setPreferences(newPreferences);
    try {
      localStorage.setItem('images-table-preferences', JSON.stringify(newPreferences));
    } catch (error) {
      console.warn('Failed to save preferences to localStorage:', error);
    }
  };

  // Save pipeline preferences to localStorage whenever they change
  const updatePipelinePreferences = (newPreferences) => {
    setPipelinePreferences(newPreferences);
    try {
      localStorage.setItem('pipelines-table-preferences', JSON.stringify(newPreferences));
    } catch (error) {
      console.warn('Failed to save pipeline preferences to localStorage:', error);
    }
  };

  // Group images by pipelineId AND name - images with same pipelineId AND name are from the same build
  // Different builds from the same pipeline will have different names (with timestamps)
  const groupedImages = React.useMemo((): GroupedImage[] => {
    if (!Array.isArray(images)) return [];
    
    // Group by pipelineId + name combination (same build distributed to multiple regions)
    const buildGroups = new Map<string, AMIImage[]>();
    const standaloneImages: AMIImage[] = [];
    
    images.forEach(image => {
      if (image.pipelineId) {
        // Use pipelineId + name as the grouping key
        // Images from the same build will have the same name
        const groupKey = `${image.pipelineId}::${image.name}`;
        const existing = buildGroups.get(groupKey) || [];
        existing.push(image);
        buildGroups.set(groupKey, existing);
      } else {
        standaloneImages.push(image);
      }
    });
    
    const result: GroupedImage[] = [];
    
    // Add grouped pipeline images
    buildGroups.forEach((buildImages, groupKey) => {
      // Sort by region to have primary region first
      const sortedImages = [...buildImages].sort((a, b) => {
        // Primary region (no sourceRegion) comes first
        if (!a.sourceRegion && b.sourceRegion) return -1;
        if (a.sourceRegion && !b.sourceRegion) return 1;
        return (a.region || '').localeCompare(b.region || '');
      });
      
      const primaryImage = sortedImages[0];
      
      // Extract base name (remove region suffix from description if present)
      const displayName = primaryImage.name;
      
      result.push({
        id: groupKey, // Use the groupKey as unique ID
        name: displayName,
        platform: primaryImage.platform,
        description: primaryImage.description?.replace(/\s*\(distributed to [^)]+\)/, '') || '',
        state: primaryImage.state,
        createdAt: primaryImage.createdAt,
        isAutoGenerated: primaryImage.isAutoGenerated,
        requiresPipeline: primaryImage.requiresPipeline,
        pipelineId: primaryImage.pipelineId,
        type: primaryImage.isAutoGenerated ? 'Base Image' : 'Pipeline',
        regions: sortedImages.map(img => ({
          region: img.region,
          amiId: img.amiId
        }))
      });
    });
    
    // Add standalone images (no pipelineId)
    standaloneImages.forEach(image => {
      result.push({
        id: image.amiId,
        name: image.name,
        platform: image.platform,
        description: image.description,
        state: image.state,
        createdAt: image.createdAt,
        isAutoGenerated: image.isAutoGenerated,
        requiresPipeline: image.requiresPipeline,
        amiId: image.amiId,
        region: image.region,
        type: image.isAutoGenerated ? 'Base Image' : 'Imported',
        regions: [{
          region: image.region,
          amiId: image.amiId
        }]
      });
    });
    
    return result;
  }, [images]);

  const visibleColumns = React.useMemo(() => {
    const allColumns = [
      {
        id: 'name',
        header: 'Name',
        cell: (item: GroupedImage) => (
          <SpaceBetween direction="horizontal" size="xs">
            <span>{item.name}</span>
            {item.requiresPipeline && (
              <Badge color="red">Pipeline Required</Badge>
            )}
          </SpaceBetween>
        ),
        sortingField: 'name'
      },
      {
        id: 'platform',
        header: 'Platform',
        cell: (item: GroupedImage) => {
          const getPlatformColor = (platform: string) => {
            switch (platform?.toLowerCase()) {
              case 'windows':
                return 'blue';
              case 'linux':
                return 'green';
              case 'macos':
                return 'grey';
              default:
                return 'blue';
            }
          };
          return (
            <Badge color={getPlatformColor(item.platform)}>
              {item.platform ? item.platform.charAt(0).toUpperCase() + item.platform.slice(1) : 'Unknown'}
            </Badge>
          );
        },
        sortingField: 'platform'
      },
      {
        id: 'regions',
        header: 'Regions',
        cell: (item: GroupedImage) => {
          // Filter out undefined regions
          const validRegions = item.regions.filter(r => r.region);
          
          if (validRegions.length === 0) {
            return <span style={{ color: '#5f6b7a' }}>-</span>;
          }
          if (validRegions.length === 1) {
            return (
              <span>
                {validRegions[0].region} <Box variant="small" display="inline" color="text-body-secondary">({validRegions[0].amiId})</Box>
              </span>
            );
          }
          // Multi-region: show expandable section with region details
          return (
            <ExpandableSection
              variant="footer"
              headerText={`${validRegions.length} regions`}
            >
              <SpaceBetween direction="vertical" size="xs">
                {validRegions.map((r, idx) => (
                  <span key={idx}>
                    <Box variant="strong" display="inline">{r.region}</Box> <Box variant="small" display="inline" color="text-body-secondary">({r.amiId})</Box>
                  </span>
                ))}
              </SpaceBetween>
            </ExpandableSection>
          );
        }
      },
      {
        id: 'type',
        header: 'Type',
        cell: (item: GroupedImage) => {
          const color = item.type === 'Base Image' ? 'grey' : item.type === 'Pipeline' ? 'blue' : 'green';
          return <Badge color={color}>{item.type}</Badge>;
        },
        sortingField: 'type'
      },
      {
        id: 'state',
        header: 'State',
        cell: (item: GroupedImage) => {
          if (!item.state) return '-';
          return item.state.charAt(0).toUpperCase() + item.state.slice(1).toLowerCase();
        },
        sortingField: 'state'
      },
      {
        id: 'createdAt',
        header: 'Created',
        cell: (item: GroupedImage) => item.createdAt ? new Date(item.createdAt).toLocaleString() : '-',
        sortingField: 'createdAt'
      }
    ];

    return preferences.contentDisplay
      .filter(item => item.visible)
      .map(item => allColumns.find(col => col.id === item.id))
      .filter(Boolean);
  }, [preferences.contentDisplay]);

  const visiblePipelineColumns = React.useMemo(() => {
    console.log('Pipeline preferences:', pipelinePreferences);
    console.log('Pipeline contentDisplay:', pipelinePreferences.contentDisplay);
    
    const allColumns = [
      {
        id: 'name',
        header: 'Name',
        cell: (item: ImagePipeline) => (
          <SpaceBetween direction="horizontal" size="xs">
            <span>{item.name}</span>
            {item.isSystemPipeline && (
              <Badge color="blue">System</Badge>
            )}
          </SpaceBetween>
        ),
        sortingField: 'name'
      },
      {
        id: 'baseOsVersion',
        header: 'Base Image',
        cell: (item: ImagePipeline) => {
          console.log('Pipeline item:', item);
          console.log('baseOsVersion:', item.baseOsVersion);
          console.log('baseImageId:', item.baseImageId);
          return item.baseOsVersion || item.baseImageId;
        },
        sortingField: 'baseOsVersion'
      },
      {
        id: 'components',
        header: 'Components',
        cell: (item: ImagePipeline) => item.components?.length || 0,
        sortingField: 'components'
      },
      {
        id: 'status',
        header: 'Status',
        cell: (item: ImagePipeline) => {
          const status = item.status || 'Unknown';
          const formatStatus = (status: string) => {
            // Handle kebab-case (e.g., 'sip-disable-complete' -> 'Sip Disable Complete')
            if (status.includes('-')) {
              return status.split('-').map(word => 
                word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()
              ).join(' ');
            }
            // Handle SCREAMING_SNAKE_CASE (e.g., 'SIP_DISABLE_COMPLETE' -> 'Sip Disable Complete')
            if (status.includes('_')) {
              return status.split('_').map(word => 
                word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()
              ).join(' ');
            }
            // Handle simple statuses (e.g., 'COMPLETED' -> 'Completed')
            return status.charAt(0).toUpperCase() + status.slice(1).toLowerCase();
          };
          
          const getStatusType = (status: string) => {
            const normalizedStatus = status.toUpperCase().replace(/-/g, '_');
            switch (normalizedStatus) {
              case 'COMPLETED':
                return 'success';
              case 'BUILDING':
                return 'in-progress';
              case 'FAILED':
              case 'SIP_DISABLE_FAILED':
                return 'error';
              case 'CREATED':
                return 'pending';
              case 'SIP_DISABLE_COMPLETE':
              case 'SIP_DISABLE_IN_PROGRESS':
              case 'SIP_DISABLE_STARTING':
                return 'in-progress';
              default:
                return 'info';
            }
          };

          return (
            <StatusIndicator type={getStatusType(status)}>
              {formatStatus(status)}
            </StatusIndicator>
          );
        },
        sortingField: 'status'
      },
      {
        id: 'createdAt',
        header: 'Created',
        cell: (item: ImagePipeline) => item.createdAt ? new Date(item.createdAt).toLocaleString() : '-',
        sortingField: 'createdAt'
      }
    ];

    const visibleColumns = pipelinePreferences.contentDisplay
      .filter(item => item.visible)
      .map(item => allColumns.find(col => col.id === item.id))
      .filter(Boolean);
    
    console.log('Visible pipeline columns:', visibleColumns);
    return visibleColumns;
  }, [pipelinePreferences.contentDisplay]);

  const [formData, setFormData] = useState({
    amiId: '',
    name: '',
    platform: '',
    description: ''
  });

  const platformOptions = [
    { label: 'Windows', value: 'windows' },
    { label: 'Linux', value: 'linux' },
    { label: 'macOS', value: 'macos' }
  ];

  // Filter options for Select dropdowns
  const typeFilterOptions = [
    { label: 'All Types', value: '' },
    { label: 'Base Image', value: 'Base Image' },
    { label: 'Pipeline', value: 'Pipeline' },
    { label: 'Imported', value: 'Imported' }
  ];

  const platformFilterOptions = [
    { label: 'All Platforms', value: '' },
    { label: 'Windows', value: 'windows' },
    { label: 'Linux', value: 'linux' },
    { label: 'macOS', value: 'macos' }
  ];

  console.log('ImageManagement: Filter options ready');

  useEffect(() => {
    fetchData();
    fetchPipelines();
  }, []);

  const fetchImages = async () => {
    const token = getAuthToken();
    if (!token) throw new Error('No current user');
    return apiCall('images', {
      headers: { 'Authorization': `Bearer ${token}` }
    });
  };

  const fetchData = async () => {
    try {
      console.log('ImageManagement: Starting fetchData');
      setLoading(true);
      const response = await fetchImages();
      console.log('ImageManagement: Got response:', response);
      const data = await response.json();
      console.log('ImageManagement: Parsed data:', data);
      console.log('ImageManagement: Is data an array?', Array.isArray(data));
      const safeData = Array.isArray(data) ? data : [];
      console.log('ImageManagement: Setting images to:', safeData);
      setImages(safeData);
    } catch (error) {
      console.error('ImageManagement: Error fetching images:', error);
      setAlert({ type: 'error', message: 'Failed to fetch images' });
      console.log('ImageManagement: Setting images to empty array due to error');
      setImages([]);
    } finally {
      setLoading(false);
      console.log('ImageManagement: fetchData completed');
    }
  };

  const fetchPipelines = async () => {
    try {
      console.log('ImageManagement: Starting fetchPipelines');
      setPipelinesLoading(true);
      
      const token = getAuthToken();
      if (!token) {
        console.error('ImageManagement: No auth token available');
        return;
      }

      const response = await apiCall('/images/pipelines', {
        method: 'GET',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        }
      });

      if (response.ok) {
        const data = await response.json();
        console.log('ImageManagement: Received pipelines:', data);
        console.log('ImageManagement: First pipeline data:', data.pipelines?.[0]);
        setPipelines(data.pipelines || []);
      } else {
        console.error('ImageManagement: Failed to fetch pipelines:', response.status);
      }
    } catch (error) {
      console.error('ImageManagement: Error fetching pipelines:', error);
    } finally {
      setPipelinesLoading(false);
    }
  };

  const fetchSoftwareLibrary = async () => {
    try {
      const token = getAuthToken();
      if (!token) {
        console.log('fetchSoftwareLibrary: No auth token');
        return;
      }

      console.log('fetchSoftwareLibrary: Fetching from /images/software...');
      const response = await apiCall('/images/software', {
        method: 'GET',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        }
      });

      console.log('fetchSoftwareLibrary: Response status:', response.status);
      
      if (response.ok) {
        const data = await response.json();
        console.log('fetchSoftwareLibrary: Raw response data:', JSON.stringify(data, null, 2));
        // Software library API returns { items: [...] }
        const items = data.items || [];
        console.log('fetchSoftwareLibrary: Setting softwareLibrary with', items.length, 'items');
        items.forEach((item, i) => {
          console.log(`  Item ${i}: name=${item.name}, componentArn=${item.componentArn}`);
        });
        setSoftwareLibrary(items);
      } else {
        console.error('fetchSoftwareLibrary: Response not OK:', response.status);
      }
    } catch (error) {
      console.error('Error fetching software library:', error);
    }
  };

  const handleEditPipelineClick = () => {
    if (selectedPipelines.length !== 1) return;
    const pipeline = selectedPipelines[0];
    setEditingPipeline(pipeline);
    setEditPipelineComponents([...pipeline.components]);
    fetchSoftwareLibrary();
    setShowEditPipelineModal(true);
  };

  const handleUpdatePipeline = async () => {
    if (!editingPipeline) return;
    
    setUpdatingPipeline(true);
    try {
      const token = getAuthToken();
      if (!token) throw new Error('No auth token');

      const response = await apiCall(`/images/pipelines/${editingPipeline.pipelineId}`, {
        method: 'PUT',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          components: editPipelineComponents
        })
      });

      if (response.ok) {
        const data = await response.json();
        setAlert({ 
          type: 'success', 
          message: `Pipeline updated successfully. New recipe version: ${data.recipeVersion}` 
        });
        setShowEditPipelineModal(false);
        setEditingPipeline(null);
        setSelectedPipelines([]);
        fetchPipelines();
      } else {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Failed to update pipeline');
      }
    } catch (error) {
      console.error('Error updating pipeline:', error);
      setAlert({ type: 'error', message: `Failed to update pipeline: ${(error as Error).message}` });
    } finally {
      setUpdatingPipeline(false);
    }
  };

  const updateComponentVersion = (index: number, newArn: string, newName: string) => {
    const updated = [...editPipelineComponents];
    updated[index] = {
      ...updated[index],
      componentArn: newArn,
      name: newName
    };
    setEditPipelineComponents(updated);
  };

  const removeComponent = (index: number) => {
    const updated = editPipelineComponents.filter((_, i) => i !== index);
    setEditPipelineComponents(updated);
  };

  const addComponent = (componentArn: string) => {
    const selectedSw = softwareLibrary.find(sw => sw.componentArn === componentArn);
    if (selectedSw) {
      setEditPipelineComponents([
        ...editPipelineComponents,
        {
          name: selectedSw.name,
          componentArn: selectedSw.componentArn,
          type: 'BUILD'
        }
      ]);
    }
  };

  // Get available components that aren't already in the pipeline
  const getAvailableComponentsToAdd = () => {
    const currentArns = new Set(editPipelineComponents.map(c => {
      // Extract base component name to avoid adding same component with different version
      const parts = c.componentArn?.split('/') || [];
      return parts[1]?.toLowerCase() || '';
    }));
    
    return softwareLibrary
      .filter(sw => {
        const swParts = sw.componentArn?.split('/') || [];
        const swName = swParts[1]?.toLowerCase() || '';
        return !currentArns.has(swName);
      })
      .map(sw => ({
        label: `${sw.name} (${sw.componentVersion || sw.versionNumber || 'Latest'})`,
        value: sw.componentArn,
        description: sw.componentArn
      }));
  };

  const getComponentOptions = (currentComponent: PipelineComponent) => {
    // Extract base component name from ARN
    // ARN format: arn:aws:imagebuilder:region:account:component/name/version/build
    const arnParts = currentComponent.componentArn?.split('/') || [];
    const componentNameFromArn = arnParts[1]?.toLowerCase() || '';
    
    console.log('getComponentOptions called for:', currentComponent.name);
    console.log('  Current component ARN:', currentComponent.componentArn);
    console.log('  Extracted component name:', componentNameFromArn);
    console.log('  Software library has', softwareLibrary.length, 'items');
    
    // Find matching components in software library by checking component name in ARN
    const matchingComponents = softwareLibrary.filter(sw => {
      const swArnParts = sw.componentArn?.split('/') || [];
      const swComponentName = swArnParts[1]?.toLowerCase() || '';
      
      console.log('  Checking software:', sw.name, 'ARN:', sw.componentArn, 'extracted name:', swComponentName);
      
      // Match by component name in ARN (e.g., both have "ffmpeg" in the ARN)
      const matches = swComponentName === componentNameFromArn;
      console.log('  Match result:', matches);
      return matches;
    });

    console.log('  Found', matchingComponents.length, 'matching components');
    
    return matchingComponents.map(sw => ({
      label: `${sw.name} (${sw.componentVersion || sw.versionNumber || 'Latest'})`,
      value: sw.componentArn,
      description: sw.componentArn
    }));
  };

  // Get all software library components for adding new ones
  const getAllSoftwareOptions = () => {
    return softwareLibrary.map(sw => ({
      label: `${sw.name} (${sw.componentVersion || sw.versionNumber || 'Latest'})`,
      value: sw.componentArn,
      description: sw.componentArn
    }));
  };

  // Validate AMI ID format (ami-xxxxxxxxxxxxxxxxx)
  const isValidAmiId = (amiId: string): boolean => {
    return /^ami-[a-f0-9]{8,17}$/.test(amiId);
  };

  const handleCreateImage = async () => {
    // Validate AMI ID format
    if (!isValidAmiId(formData.amiId)) {
      setAlert({ 
        type: 'error', 
        message: 'Invalid AMI ID format. AMI IDs must start with "ami-" followed by 8-17 hexadecimal characters (e.g., ami-0123456789abcdef0)' 
      });
      return;
    }

    try {
      const token = getAuthToken();
      if (!token) throw new Error('No current user');
      
      const response = await apiCall('images', {
        method: 'POST',
        headers: { 
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(formData)
      });
      
      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`API Error: ${response.status} - ${errorText}`);
      }
      
      setAlert({ type: 'success', message: 'Image created successfully' });
      setShowCreateModal(false);
      setFormData({ amiId: '', name: '', platform: '', description: '' });
      fetchData();
    } catch (error) {
      console.error('Error creating image:', error);
      setAlert({ type: 'error', message: `Failed to create image: ${error.message}` });
    }
  };

  const handleUpdateImage = async () => {
    if (!editingImage) return;
    
    try {
      const token = getAuthToken();
      if (!token) throw new Error('No current user');
      
      await apiCall(`images/${editingImage.amiId}`, {
        method: 'PUT',
        headers: { 
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          name: formData.name,
          platform: formData.platform,
          description: formData.description
        })
      });
      setAlert({ type: 'success', message: 'Image updated successfully' });
      setShowEditModal(false);
      setEditingImage(null);
      fetchData();
    } catch (error) {
      console.error('Error updating image:', error);
      setAlert({ type: 'error', message: 'Failed to update image' });
    }
  };

  const deletePipeline = async () => {
    if (selectedPipelines.length === 0) return;
    
    setDeleting(true);
    try {
      const token = getAuthToken();
      
      // Delete multiple pipelines
      await Promise.all(selectedPipelines.map(pipeline => 
        apiCall(`/images/pipelines/${pipeline.pipelineId}`, {
          method: 'DELETE',
          headers: { 'Authorization': `Bearer ${token}` }
        })
      ));

      setAlert({ 
        type: 'success', 
        message: `${selectedPipelines.length} pipeline(s) deleted successfully` 
      });
      setSelectedPipelines([]);
      setShowDeletePipelineModal(false);
      fetchPipelines();
    } catch (error) {
      console.error('Error deleting pipelines:', error);
      setAlert({ type: 'error', message: 'Failed to delete pipeline(s)' });
    } finally {
      setDeleting(false);
    }
  };

  const buildPipelines = async () => {
    if (selectedPipelines.length === 0) return;
    
    setBuilding(true);
    try {
      const token = getAuthToken();
      
      // Build multiple pipelines
      await Promise.all(selectedPipelines.map(pipeline => 
        apiCall(`/images/pipelines/${pipeline.pipelineId}/execute`, {
          method: 'POST',
          headers: { 'Authorization': `Bearer ${token}` }
        })
      ));

      setAlert({ 
        type: 'success', 
        message: `${selectedPipelines.length} pipeline build(s) started successfully` 
      });
      fetchPipelines();
    } catch (error) {
      console.error('Error starting pipeline builds:', error);
      setAlert({ type: 'error', message: 'Failed to start pipeline build(s)' });
    } finally {
      setBuilding(false);
    }
  };

  const handleDeleteImages = async () => {
    if (selectedItems.length === 0) return;
    
    setDeleting(true);
    try {
      const token = getAuthToken();
      if (!token) throw new Error('No current user');
      
      // For grouped images, delete all regional AMIs
      const deletePromises: Promise<Response>[] = [];
      selectedItems.forEach(image => {
        // Delete all AMIs in the regions array
        image.regions.forEach(r => {
          deletePromises.push(
            apiCall(`images/${r.amiId}`, {
              method: 'DELETE',
              headers: { 'Authorization': `Bearer ${token}` }
            })
          );
        });
      });
      
      await Promise.all(deletePromises);
      
      setAlert({ type: 'success', message: `${selectedItems.length} image(s) removed from management successfully` });
      setSelectedItems([]);
      setShowDeleteModal(false);
      fetchData();
    } catch (error) {
      console.error('Error deleting images:', error);
      setAlert({ type: 'error', message: 'Failed to remove images from management' });
    } finally {
      setDeleting(false);
    }
  };

  const handleEditClick = () => {
    if (selectedItems.length !== 1) return;
    const image = selectedItems[0];
    
    // Check if it's an auto-generated AMI
    if (image.isAutoGenerated) {
      setAlert({
        type: 'error',
        message: 'Cannot edit auto-generated AMI. This AMI is automatically managed by AWS and always reflects the latest version.'
      });
      return;
    }
    
    // For grouped images, we edit the primary AMI (first in regions array)
    const primaryAmiId = image.amiId || image.regions[0]?.amiId || '';
    
    // Convert GroupedImage to AMIImage for editing
    const editableImage: AMIImage = {
      amiId: primaryAmiId,
      name: image.name,
      platform: image.platform,
      description: image.description,
      state: image.state,
      createdAt: image.createdAt,
      isAutoGenerated: image.isAutoGenerated,
      requiresPipeline: image.requiresPipeline,
      pipelineId: image.pipelineId,
      region: image.region || image.regions[0]?.region
    };
    
    setEditingImage(editableImage);
    setFormData({
      amiId: primaryAmiId,
      name: image.name,
      platform: image.platform,
      description: image.description || ''
    });
    setShowEditModal(true);
  };

  const filteredImages = React.useMemo((): GroupedImage[] => {
    console.log('ImageManagement: filteredImages useMemo called');
    console.log('ImageManagement: groupedImages:', groupedImages);
    
    if (!Array.isArray(groupedImages)) {
      console.log('ImageManagement: groupedImages is not an array, returning empty array');
      return [];
    }
    
    let filtered = [...groupedImages];
    console.log('ImageManagement: Starting with filtered:', filtered);

    // Apply text filter (searches name, platform, amiId)
    if (filteringText) {
      const searchText = filteringText.toLowerCase();
      filtered = filtered.filter(image => 
        image.name?.toLowerCase().includes(searchText) ||
        image.platform?.toLowerCase().includes(searchText) ||
        image.regions?.some(r => r.amiId?.toLowerCase().includes(searchText))
      );
    }

    // Apply type filter
    if (typeFilter?.value) {
      filtered = filtered.filter(image => image.type === typeFilter.value);
    }

    // Apply platform filter
    if (platformFilter?.value) {
      filtered = filtered.filter(image => image.platform?.toLowerCase() === platformFilter.value.toLowerCase());
    }

    // Apply sorting
    if (sortingColumn.sortingField) {
      console.log('ImageManagement: Applying sorting:', sortingColumn);
      filtered = [...filtered].sort((a, b) => {
        const aValue = a[sortingColumn.sortingField as keyof GroupedImage] || '';
        const bValue = b[sortingColumn.sortingField as keyof GroupedImage] || '';
        if (aValue < bValue) return sortingColumn.sortingDescending ? 1 : -1;
        if (aValue > bValue) return sortingColumn.sortingDescending ? -1 : 1;
        return 0;
      });
      console.log('ImageManagement: After sorting:', filtered);
    }

    console.log('ImageManagement: Final filtered result:', filtered);
    return filtered;
  }, [groupedImages, filteringText, typeFilter, platformFilter, sortingColumn]);

  const filteredPipelines = React.useMemo(() => {
    if (!Array.isArray(pipelines)) {
      return [];
    }
    
    let filtered = [...pipelines];

    // Apply PropertyFilter
    if (pipelineFilteringText.tokens.length > 0) {
      filtered = filtered.filter(pipeline => {
        return pipelineFilteringText.tokens.every(token => {
          const { propertyKey, operator, value } = token;
          let itemValue = pipeline[propertyKey as keyof ImagePipeline];
          
          if (typeof itemValue === 'string') {
            itemValue = itemValue.toLowerCase();
          }
          const filterValue = value.toLowerCase();
          
          switch (operator) {
            case '=':
              return itemValue === filterValue;
            case '!=':
              return itemValue !== filterValue;
            case ':':
              return itemValue && typeof itemValue === 'string' && itemValue.includes(filterValue);
            case '!:':
              return !itemValue || (typeof itemValue === 'string' && !itemValue.includes(filterValue));
            default:
              return true;
          }
        });
      });
    }

    // Apply sorting
    if (pipelineSortingColumn.sortingField) {
      filtered = [...filtered].sort((a, b) => {
        let aValue: any = a[pipelineSortingColumn.sortingField as keyof ImagePipeline];
        let bValue: any = b[pipelineSortingColumn.sortingField as keyof ImagePipeline];
        
        // Handle components field (sort by count)
        if (pipelineSortingColumn.sortingField === 'components') {
          aValue = Array.isArray(aValue) ? aValue.length : 0;
          bValue = Array.isArray(bValue) ? bValue.length : 0;
        } else {
          aValue = aValue || '';
          bValue = bValue || '';
        }
        
        if (aValue < bValue) return pipelineSortingColumn.sortingDescending ? 1 : -1;
        if (aValue > bValue) return pipelineSortingColumn.sortingDescending ? -1 : 1;
        return 0;
      });
    }

    return filtered;
  }, [pipelines, pipelineFilteringText, pipelineSortingColumn]);

  // Paginated items for Images table
  const paginatedImages = React.useMemo(() => {
    const startIndex = (currentPageIndex - 1) * preferences.pageSize;
    return filteredImages.slice(startIndex, startIndex + preferences.pageSize);
  }, [filteredImages, currentPageIndex, preferences.pageSize]);

  // Paginated items for Pipelines table
  const paginatedPipelines = React.useMemo(() => {
    const startIndex = (pipelineCurrentPageIndex - 1) * pipelinePreferences.pageSize;
    return filteredPipelines.slice(startIndex, startIndex + pipelinePreferences.pageSize);
  }, [filteredPipelines, pipelineCurrentPageIndex, pipelinePreferences.pageSize]);

  // Reset page index when filters change
  useEffect(() => {
    setCurrentPageIndex(1);
  }, [filteringText, typeFilter, platformFilter]);

  useEffect(() => {
    setPipelineCurrentPageIndex(1);
  }, [pipelineFilteringText]);

  return (
    <>
      <AppLayout
        navigation={<Navigation isAdmin={true} productName={config?.productName} acronym={config?.acronym} />}
        disableContentPaddings={true}
        toolsHide={true}
        content={
          <ContentLayout
            defaultPadding
            headerVariant="high-contrast"
            maxContentWidth={1800}
            breadcrumbs={
              <BreadcrumbGroup
                items={[
                  { text: 'Dashboard', href: '/dashboard' },
                  { text: 'Images' }
                ]}
                ariaLabel="Breadcrumbs"
              />
            }
            header={
              <Box padding={{ vertical: "l" }}>
                <div style={{ maxWidth: '1200px' }}>
                <Grid
                  gridDefinition={[
                    { colspan: { default: 12 } }
                  ]}
                >
                  <div>
                    <Box variant="h1" fontSize="display-l">
                      Image Management
                    </Box>
                    <Box
                      variant="p"
                      color="text-body-secondary"
                      margin={{ top: "xxs", bottom: "s" }}
                    >
                      Manage images available for workstation creation. Configure and maintain the approved image catalog.
                    </Box>
                  </div>
                </Grid>
                </div>
              </Box>
            }
          >
          <SpaceBetween size="l">
            {alert && (
              <Alert
                type={alert.type}
                dismissible
                onDismiss={() => setAlert(null)}
              >
                {alert.message}
              </Alert>
            )}

            <Table
              header={
                <Header
                  counter={
                    selectedItems.length
                      ? `(${selectedItems.length}/${filteredImages.length})`
                      : `(${filteredImages.length})`
                  }
                  actions={
                    <SpaceBetween direction="horizontal" size="xs">
                      <Button
                        iconName="refresh"
                        onClick={fetchData}
                        loading={loading}
                      />
                      <Button 
                        onClick={handleEditClick}
                        disabled={selectedItems.length !== 1}
                      >
                        Edit
                      </Button>
                      <Button 
                        onClick={() => {
                          // Check if any selected items are auto-generated
                          const autoGeneratedItems = selectedItems.filter(item => item.isAutoGenerated);
                          if (autoGeneratedItems.length > 0) {
                            setAlert({
                              type: 'error',
                              message: `Cannot delete auto-generated AMI${autoGeneratedItems.length > 1 ? 's' : ''}. These AMIs are automatically managed by AWS.`
                            });
                            return;
                          }
                          setShowDeleteModal(true);
                        }}
                        disabled={selectedItems.length === 0}
                      >
                        Remove
                      </Button>
                      <Button 
                        onClick={() => {
                          if (selectedItems.length === 1) {
                            const image = selectedItems[0];
                            // Check if image requires pipeline processing
                            if (image.requiresPipeline) {
                              setAlert({
                                type: 'error',
                                message: 'This image requires pipeline processing before it can be used to create workstations.'
                              });
                              return;
                            }
                            // Navigate to workstations page with create modal
                            // For grouped images (multi-region), pass the groupKey (id) which is pipelineId::name
                            // For standalone images, pass the amiId directly
                            if (image.pipelineId && image.regions.length > 1) {
                              // Use image.id which is the groupKey (pipelineId::name)
                              window.location.href = `/workstations?create=true&pipelineId=${encodeURIComponent(image.id)}`;
                            } else {
                              // Single region image - pass the amiId directly
                              const amiId = image.amiId || image.regions[0]?.amiId;
                              window.location.href = `/workstations?create=true&imageId=${encodeURIComponent(amiId)}`;
                            }
                          }
                        }}
                        disabled={selectedItems.length !== 1}
                      >
                        Create Workstation
                      </Button>
                      <Button variant="primary" onClick={() => setShowCreateModal(true)}>Import Image</Button>
                    </SpaceBetween>
                  }
                >
                  Images
                </Header>
              }
              columnDefinitions={visibleColumns}
              items={paginatedImages}
              loading={loading}
              loadingText="Loading images..."
              selectedItems={selectedItems}
              onSelectionChange={({ detail }) => setSelectedItems(detail.selectedItems)}
              selectionType="multi"
              trackBy="id"
              wrapLines={preferences.wrapLines}
              stripedRows={preferences.stripedRows}
              contentDensity={preferences.contentDensity}
              stickyColumns={preferences.stickyColumns}
              pagination={
                <Pagination
                  currentPageIndex={currentPageIndex}
                  pagesCount={Math.ceil(filteredImages.length / preferences.pageSize)}
                  onChange={({ detail }) => setCurrentPageIndex(detail.currentPageIndex)}
                  ariaLabels={{
                    nextPageLabel: 'Next page',
                    previousPageLabel: 'Previous page',
                    pageLabel: (pageNumber) => `Page ${pageNumber} of all pages`
                  }}
                />
              }
              preferences={
                <CollectionPreferences
                  title="Preferences"
                  confirmLabel="Confirm"
                  cancelLabel="Cancel"
                  onConfirm={({ detail }) => updatePreferences(detail)}
                  preferences={preferences}
                  pageSizePreference={{
                    title: "Page size",
                    options: [
                      { value: 10, label: "10 images" },
                      { value: 20, label: "20 images" },
                      { value: 50, label: "50 images" }
                    ]
                  }}
                  wrapLinesPreference={{
                    label: "Wrap lines",
                    description: "Wrap text content in table cells"
                  }}
                  stripedRowsPreference={{
                    label: "Striped rows",
                    description: "Add alternating row colors"
                  }}
                  contentDensityPreference={{
                    label: "Compact mode",
                    description: "Display content in a denser, more compact mode"
                  }}
                  contentDisplayPreference={{
                    title: "Column preferences",
                    description: "Customize which columns are displayed",
                    options: [
                      { id: "name", label: "Name", alwaysVisible: true },
                      { id: "platform", label: "Platform" },
                      { id: "regions", label: "Regions" },
                      { id: "type", label: "Type" },
                      { id: "state", label: "State" },
                      { id: "createdAt", label: "Imported" }
                    ]
                  }}
                  stickyColumnsPreference={{
                    firstColumns: {
                      title: "Stick first column(s)",
                      description: "Keep the first column(s) visible while horizontally scrolling",
                      options: [
                        { label: "None", value: 0 },
                        { label: "First column", value: 1 },
                        { label: "First two columns", value: 2 }
                      ]
                    },
                    lastColumns: {
                      title: "Stick last column",
                      description: "Keep the last column visible while horizontally scrolling",
                      options: [
                        { label: "None", value: 0 },
                        { label: "Last column", value: 1 }
                      ]
                    }
                  }}
                />
              }
              empty={
                <Box textAlign="center" color="inherit">
                  <b>No images</b>
                  <Box padding={{ bottom: 's' }} variant="p" color="inherit">
                    No images to display.
                  </Box>
                  <Button variant="primary" onClick={() => setShowCreateModal(true)}>Import Image</Button>
                </Box>
              }
              filter={
                <SpaceBetween direction="horizontal" size="s">
                  <TextFilter
                    filteringText={filteringText}
                    filteringPlaceholder="Search by name or AMI ID"
                    filteringAriaLabel="Filter images"
                    onChange={({ detail }) => setFilteringText(detail.filteringText)}
                  />
                  <Select
                    selectedOption={typeFilter}
                    onChange={({ detail }) => setTypeFilter(detail.selectedOption?.value ? detail.selectedOption : null)}
                    options={typeFilterOptions}
                    placeholder="Type"
                    selectedAriaLabel="Selected type"
                  />
                  <Select
                    selectedOption={platformFilter}
                    onChange={({ detail }) => setPlatformFilter(detail.selectedOption?.value ? detail.selectedOption : null)}
                    options={platformFilterOptions}
                    placeholder="Platform"
                    selectedAriaLabel="Selected platform"
                  />
                </SpaceBetween>
              }
              sortingColumn={sortingColumn}
              sortingDescending={sortingColumn.sortingDescending}
              onSortingChange={({ detail }) => {
                setSortingColumn({
                  sortingField: detail.sortingColumn.sortingField,
                  sortingDescending: detail.isDescending || false
                });
              }}
            />

            {/* Create Modal */}
            <Modal
              visible={showCreateModal}
              onDismiss={() => setShowCreateModal(false)}
              header="Import New Image"
              footer={
                <Box float="right">
                  <SpaceBetween direction="horizontal" size="xs">
                    <Button variant="link" onClick={() => setShowCreateModal(false)}>
                      Cancel
                    </Button>
                    <Button 
                      variant="primary" 
                      onClick={handleCreateImage}
                      disabled={!formData.amiId || !formData.name || !formData.platform || (formData.amiId && !isValidAmiId(formData.amiId))}
                    >
                      Import
                    </Button>
                  </SpaceBetween>
                </Box>
              }
            >
              <SpaceBetween size="m">
                <FormField 
                  label="AMI ID" 
                  description="Enter the AWS AMI ID (e.g., ami-0123456789abcdef0)"
                  errorText={formData.amiId && !isValidAmiId(formData.amiId) ? 'Invalid AMI ID format. Must start with "ami-" followed by 8-17 hex characters.' : undefined}
                >
                  <Input
                    value={formData.amiId}
                    onChange={({ detail }) => setFormData({ ...formData, amiId: detail.value })}
                    placeholder="ami-0123456789abcdef0"
                    invalid={formData.amiId ? !isValidAmiId(formData.amiId) : false}
                  />
                </FormField>
                <FormField label="Name">
                  <Input
                    value={formData.name}
                    onChange={({ detail }) => setFormData({ ...formData, name: detail.value })}
                    placeholder="Enter image name"
                  />
                </FormField>
                <FormField label="Platform">
                  <Select
                    selectedOption={platformOptions.find(opt => opt.value === formData.platform) || null}
                    onChange={({ detail }) => setFormData({ ...formData, platform: detail.selectedOption?.value || '' })}
                    options={platformOptions}
                    placeholder="Select platform"
                  />
                </FormField>
                <FormField label="Description" description="Optional description">
                  <Textarea
                    value={formData.description}
                    onChange={({ detail }) => setFormData({ ...formData, description: detail.value })}
                    placeholder="Enter description"
                  />
                </FormField>
              </SpaceBetween>
            </Modal>

            {/* Edit Modal */}
            <Modal
              visible={showEditModal}
              onDismiss={() => setShowEditModal(false)}
              header="Edit Image"
              footer={
                <Box float="right">
                  <SpaceBetween direction="horizontal" size="xs">
                    <Button variant="link" onClick={() => setShowEditModal(false)}>
                      Cancel
                    </Button>
                    <Button 
                      variant="primary" 
                      onClick={handleUpdateImage}
                      disabled={!formData.name || !formData.platform}
                    >
                      Update
                    </Button>
                  </SpaceBetween>
                </Box>
              }
            >
              <SpaceBetween size="m">
                <FormField label="AMI ID" description="AMI ID cannot be changed">
                  <Input
                    value={formData.amiId}
                    disabled
                  />
                </FormField>
                <FormField label="Name">
                  <Input
                    value={formData.name}
                    onChange={({ detail }) => setFormData({ ...formData, name: detail.value })}
                    placeholder="Enter image name"
                  />
                </FormField>
                <FormField label="Platform">
                  <Select
                    selectedOption={platformOptions.find(opt => opt.value === formData.platform) || null}
                    onChange={({ detail }) => setFormData({ ...formData, platform: detail.selectedOption?.value || '' })}
                    options={platformOptions}
                    placeholder="Select platform"
                  />
                </FormField>
                <FormField label="Description" description="Optional description">
                  <Textarea
                    value={formData.description}
                    onChange={({ detail }) => setFormData({ ...formData, description: detail.value })}
                    placeholder="Enter description"
                  />
                </FormField>
              </SpaceBetween>
            </Modal>

            {/* Pipelines Table */}
            <Table
              header={
                <Header
                  counter={
                    selectedPipelines.length
                      ? `(${selectedPipelines.length}/${filteredPipelines.length})`
                      : `(${filteredPipelines.length})`
                  }
                  actions={
                    <SpaceBetween direction="horizontal" size="xs">
                      <Button iconName="refresh" onClick={fetchPipelines} loading={pipelinesLoading} />
                      <Button 
                        disabled={selectedPipelines.length !== 1}
                        onClick={handleEditPipelineClick}
                      >
                        Edit
                      </Button>
                      <Button 
                        disabled={selectedPipelines.length === 0 || selectedPipelines.some(p => p.isSystemPipeline)}
                        onClick={() => setShowDeletePipelineModal(true)}
                      >
                        Delete
                      </Button>
                      <Button 
                        disabled={selectedPipelines.length === 0 || building}
                        loading={building}
                        onClick={buildPipelines}
                      >
                        Build Image
                      </Button>
                      <Button variant="primary" onClick={() => window.location.href = '/images/create'}>
                        Create Pipeline
                      </Button>
                    </SpaceBetween>
                  }
                >
                  Image Pipelines
                </Header>
              }
              columnDefinitions={visiblePipelineColumns}
              items={paginatedPipelines}
              loading={pipelinesLoading}
              loadingText="Loading pipelines..."
              selectedItems={selectedPipelines}
              onSelectionChange={({ detail }) => setSelectedPipelines(detail.selectedItems)}
              selectionType="multi"
              trackBy="pipelineId"
              pagination={
                <Pagination
                  currentPageIndex={pipelineCurrentPageIndex}
                  pagesCount={Math.ceil(filteredPipelines.length / pipelinePreferences.pageSize)}
                  onChange={({ detail }) => setPipelineCurrentPageIndex(detail.currentPageIndex)}
                  ariaLabels={{
                    nextPageLabel: 'Next page',
                    previousPageLabel: 'Previous page',
                    pageLabel: (pageNumber) => `Page ${pageNumber} of all pages`
                  }}
                />
              }
              filter={
                <PropertyFilter
                  query={pipelineFilteringText}
                  onChange={({ detail }) => setPipelineFilteringText(detail)}
                  filteringProperties={[
                    {
                      key: 'name',
                      operators: [':', '!:', '=', '!='],
                      propertyLabel: 'Name',
                      groupValuesLabel: 'Name values'
                    },
                    {
                      key: 'baseImageId',
                      operators: [':', '!:', '=', '!='],
                      propertyLabel: 'Base Image',
                      groupValuesLabel: 'Base Image values'
                    },
                    {
                      key: 'status',
                      operators: [':', '!:', '=', '!='],
                      propertyLabel: 'Status',
                      groupValuesLabel: 'Status values'
                    }
                  ]}
                  filteringOptions={[
                    ...pipelines.map(pipeline => ({ propertyKey: 'name', value: pipeline.name })),
                    ...pipelines.map(pipeline => ({ propertyKey: 'baseImageId', value: pipeline.baseImageId })),
                    { propertyKey: 'status', value: 'CREATED' },
                    { propertyKey: 'status', value: 'BUILDING' },
                    { propertyKey: 'status', value: 'COMPLETED' },
                    { propertyKey: 'status', value: 'FAILED' }
                  ].filter((option, index, self) => 
                    index === self.findIndex(o => o.propertyKey === option.propertyKey && o.value === option.value)
                  )}
                  filteringPlaceholder="Find pipelines"
                  filteringAriaLabel="Filter pipelines"
                  i18nStrings={{
                    filteringAriaLabel: "Filter pipelines",
                    dismissAriaLabel: "Dismiss",
                    filteringPlaceholder: "Filter pipelines",
                    groupValuesText: "Values",
                    groupPropertiesText: "Properties",
                    operatorsText: "Operators",
                    operationAndText: "and",
                    operationOrText: "or",
                    operatorLessText: "Less than",
                    operatorLessOrEqualText: "Less than or equal",
                    operatorGreaterText: "Greater than",
                    operatorGreaterOrEqualText: "Greater than or equal",
                    operatorContainsText: "Contains",
                    operatorDoesNotContainText: "Does not contain",
                    operatorEqualsText: "Equals",
                    operatorDoesNotEqualText: "Does not equal",
                    editTokenText: "Edit filter",
                    propertyText: "Property",
                    operatorText: "Operator",
                    valueText: "Value",
                    cancelActionText: "Cancel",
                    applyActionText: "Apply",
                    allPropertiesLabel: "All properties",
                    tokenLimitShowMore: "Show more",
                    tokenLimitShowFewer: "Show fewer",
                    clearFiltersText: "Clear filters",
                    removeTokenButtonAriaLabel: (token) => `Remove token ${token.propertyKey} ${token.operator} ${token.value}`,
                    enteredTextLabel: (text) => `Use: "${text}"`
                  }}
                />
              }
              sortingColumn={pipelineSortingColumn}
              sortingDescending={pipelineSortingColumn.sortingDescending}
              onSortingChange={({ detail }) => {
                setPipelineSortingColumn({
                  sortingField: detail.sortingColumn.sortingField,
                  sortingDescending: detail.isDescending || false
                });
              }}
              preferences={
                <CollectionPreferences
                  title="Preferences"
                  confirmLabel="Confirm"
                  cancelLabel="Cancel"
                  preferences={pipelinePreferences}
                  onConfirm={({ detail }) => updatePipelinePreferences(detail)}
                  pageSizePreference={{
                    title: 'Page size',
                    options: [
                      { value: 10, label: '10 pipelines' },
                      { value: 20, label: '20 pipelines' },
                      { value: 50, label: '50 pipelines' }
                    ]
                  }}
                  wrapLinesPreference={{
                    label: 'Wrap lines',
                    description: 'Check to see all the text and wrap the lines'
                  }}
                  contentDisplayPreference={{
                    title: 'Column preferences',
                    description: 'Customize which columns are displayed',
                    options: [
                      { id: 'name', label: 'Name', alwaysVisible: true },
                      { id: 'baseOsVersion', label: 'Base Image' },
                      { id: 'components', label: 'Components' },
                      { id: 'status', label: 'Status' },
                      { id: 'createdAt', label: 'Created' }
                    ]
                  }}
                />
              }
              empty={
                <Box textAlign="center" color="inherit">
                  <b>No pipelines</b>
                  <Box padding={{ bottom: 's' }} variant="p" color="inherit">
                    No image pipelines to display.
                  </Box>
                  <Button onClick={() => window.location.href = '/images/create'}>Create Pipeline</Button>
                </Box>
              }
            />

            {/* Delete Confirmation Modal */}
            <Modal
              visible={showDeleteModal}
              onDismiss={() => setShowDeleteModal(false)}
              header="Remove Images from Management"
              footer={
                <SpaceBetween direction="horizontal" size="xs">
                  <Button variant="link" onClick={() => setShowDeleteModal(false)}>
                    Cancel
                  </Button>
                  <Button 
                    variant="primary"
                    loading={deleting}
                    onClick={handleDeleteImages}
                  >
                    Remove from Management
                  </Button>
                </SpaceBetween>
              }
            >
              <SpaceBetween direction="vertical" size="m">
                <Alert type="info">
                  <strong>Note:</strong> This will only remove the images from Image Management. The actual AMI will remain in your AWS account and can be re-imported later.
                </Alert>
                <Box>
                  Are you sure you want to remove the following {selectedItems.length} image(s) from management?
                </Box>
                <ul>
                  {selectedItems.map((image: any) => (
                    <li key={image.amiId}>{image.name} ({image.amiId})</li>
                  ))}
                </ul>
              </SpaceBetween>
            </Modal>

            {/* Delete Pipeline Confirmation Modal */}
            <Modal
              visible={showDeletePipelineModal}
              onDismiss={() => setShowDeletePipelineModal(false)}
              header={`Delete ${selectedPipelines.length === 1 ? 'Pipeline' : 'Pipelines'}`}
              footer={
                <SpaceBetween direction="horizontal" size="xs">
                  <Button variant="link" onClick={() => setShowDeletePipelineModal(false)}>
                    Cancel
                  </Button>
                  <Button
                    variant="primary"
                    loading={deleting}
                    onClick={deletePipeline}
                  >
                    Delete {selectedPipelines.length === 1 ? 'Pipeline' : 'Pipelines'}
                  </Button>
                </SpaceBetween>
              }
            >
              <SpaceBetween direction="vertical" size="m">
                <Alert type="warning">
                  <strong>Warning:</strong> This action cannot be undone.
                </Alert>
                <Box>
                  Are you sure you want to delete {selectedPipelines.length === 1 ? 'the pipeline' : `${selectedPipelines.length} pipelines`}?
                  {selectedPipelines.length === 1 && (
                    <> <strong>{selectedPipelines[0]?.name}</strong></>
                  )}
                  {selectedPipelines.length > 1 && (
                    <ul>
                      {selectedPipelines.map(pipeline => (
                        <li key={pipeline.pipelineId}><strong>{pipeline.name}</strong></li>
                      ))}
                    </ul>
                  )}
                </Box>
                <Box>
                  <strong>This will permanently delete:</strong>
                </Box>
                <ul>
                  <li>Image Builder Pipeline{selectedPipelines.length > 1 ? 's' : ''}</li>
                  <li>Image Recipe{selectedPipelines.length > 1 ? 's' : ''}</li>
                  <li>Infrastructure Configuration{selectedPipelines.length > 1 ? 's' : ''}</li>
                  <li>Distribution Configuration{selectedPipelines.length > 1 ? 's' : ''}</li>
                  <li>Custom Components (if any)</li>
                  <li>Associated AMIs from your account</li>
                  <li>AMI records from the management system</li>
                </ul>
              </SpaceBetween>
            </Modal>

            {/* Edit Pipeline Modal */}
            <Modal
              visible={showEditPipelineModal}
              onDismiss={() => {
                setShowEditPipelineModal(false);
                setEditingPipeline(null);
              }}
              header="Edit Pipeline Components"
              size="large"
              footer={
                <SpaceBetween direction="horizontal" size="xs">
                  <Button variant="link" onClick={() => {
                    setShowEditPipelineModal(false);
                    setEditingPipeline(null);
                  }}>
                    Cancel
                  </Button>
                  <Button
                    variant="primary"
                    loading={updatingPipeline}
                    onClick={handleUpdatePipeline}
                    disabled={editPipelineComponents.length === 0}
                  >
                    Update Pipeline
                  </Button>
                </SpaceBetween>
              }
            >
              <SpaceBetween direction="vertical" size="m">
                <Alert type="info">
                  Updating components will create a new recipe version. The pipeline will use the updated recipe for future builds.
                </Alert>
                
                {editingPipeline && (
                  <>
                    <FormField label="Pipeline Name">
                      <Input value={editingPipeline.name} disabled />
                    </FormField>
                    
                    <FormField label="Base Image">
                      <Input value={editingPipeline.baseOsVersion || editingPipeline.baseImageId} disabled />
                    </FormField>

                    <FormField 
                      label="Components" 
                      description="Select component versions or remove components. Components from the Software Library can be swapped for different versions."
                    >
                      <SpaceBetween direction="vertical" size="s">
                        {editPipelineComponents.map((component, index) => {
                          const options = getComponentOptions(component);
                          const currentOption = options.find(opt => opt.value === component.componentArn);
                          const allOptions = getAllSoftwareOptions();
                          
                          return (
                            <div key={index} style={{ display: 'flex', alignItems: 'flex-start', gap: '8px' }}>
                              <div style={{ flex: 1 }}>
                                <FormField label={component.name}>
                                  {options.length > 0 ? (
                                    <Select
                                      selectedOption={currentOption || { 
                                        label: `${component.name} (current)`, 
                                        value: component.componentArn 
                                      }}
                                      onChange={({ detail }) => {
                                        if (detail.selectedOption?.value) {
                                          const selectedSw = softwareLibrary.find(
                                            sw => sw.componentArn === detail.selectedOption.value
                                          );
                                          updateComponentVersion(
                                            index, 
                                            detail.selectedOption.value,
                                            selectedSw?.name || component.name
                                          );
                                        }
                                      }}
                                      options={[
                                        { 
                                          label: `${component.name} (current)`, 
                                          value: component.componentArn,
                                          description: component.componentArn
                                        },
                                        ...options.filter(opt => opt.value !== component.componentArn)
                                      ]}
                                      placeholder="Select version"
                                    />
                                  ) : allOptions.length > 0 ? (
                                    <Select
                                      selectedOption={{ 
                                        label: `${component.name} (current - not in library)`, 
                                        value: component.componentArn 
                                      }}
                                      onChange={({ detail }) => {
                                        if (detail.selectedOption?.value && detail.selectedOption.value !== component.componentArn) {
                                          const selectedSw = softwareLibrary.find(
                                            sw => sw.componentArn === detail.selectedOption.value
                                          );
                                          updateComponentVersion(
                                            index, 
                                            detail.selectedOption.value,
                                            selectedSw?.name || component.name
                                          );
                                        }
                                      }}
                                      options={[
                                        { 
                                          label: `${component.name} (current - not in library)`, 
                                          value: component.componentArn,
                                          description: component.componentArn
                                        },
                                        ...allOptions
                                      ]}
                                      placeholder="Replace with library component"
                                    />
                                  ) : (
                                    <Box color="text-status-inactive">
                                      {component.componentArn}
                                      <Box variant="small" color="text-body-secondary">
                                        No components in software library
                                      </Box>
                                    </Box>
                                  )}
                                </FormField>
                              </div>
                              <div style={{ paddingTop: '24px' }}>
                                <Button
                                  iconName="remove"
                                  variant="icon"
                                  onClick={() => removeComponent(index)}
                                  ariaLabel={`Remove ${component.name}`}
                                />
                              </div>
                            </div>
                          );
                        })}
                        {editPipelineComponents.length === 0 && (
                          <Alert type="warning">
                            At least one component is required. Add a component or cancel to keep the current configuration.
                          </Alert>
                        )}
                      </SpaceBetween>
                    </FormField>

                    <FormField 
                      label="Add Component" 
                      description="Add additional components from the Software Library to this pipeline."
                    >
                      {getAvailableComponentsToAdd().length > 0 ? (
                        <Select
                          selectedOption={null}
                          onChange={({ detail }) => {
                            if (detail.selectedOption?.value) {
                              addComponent(detail.selectedOption.value);
                            }
                          }}
                          options={getAvailableComponentsToAdd()}
                          placeholder="Select a component to add..."
                          filteringType="auto"
                        />
                      ) : (
                        <Box color="text-status-inactive">
                          {softwareLibrary.length === 0 
                            ? "No components available in the Software Library. Add components in the Software page first."
                            : "All available components are already in this pipeline."}
                        </Box>
                      )}
                    </FormField>
                  </>
                )}
              </SpaceBetween>
            </Modal>
          </SpaceBetween>
          </ContentLayout>
        }
      />
    </>
  );
};

export default ImageManagement;
