// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import React, { useState, useEffect, useRef, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import type { InputRef } from 'antd';
import {
  Card,
  Steps,
  Button,
  Form,
  Input,
  Select,
  Typography,
  Breadcrumb,
  Space,
  Alert,
  Modal,
  Tag,
  Tabs,
  Table,
  Checkbox,
  Row,
  Col,
  Empty,
  Spin,
  Descriptions,
  Divider,
} from 'antd';
import {
  HomeOutlined,
  PlusOutlined,
  DeleteOutlined,
  ReloadOutlined,
  CodeOutlined,
} from '@ant-design/icons';
import type { ColumnsType } from 'antd/es/table';
import AppLayoutAntd from '../components/AppLayoutAntd';
import AddSoftwareWizardAntd from '../components/AddSoftwareWizardAntd';
import { apiCall } from '../utils/api';
import { getAuthToken } from '../utils/auth';

const { Title, Text } = Typography;
const { TextArea } = Input;

interface SoftwareComponent {
  softwareId: string;
  name: string;
  versionNumber: string;
  category: string;
  description: string;
  componentArn: string;
  estimatedInstallTime: string;
  diskSpaceRequired: string;
  gpuRequired?: boolean;
  platform?: string;
  parameters?: { name: string; description?: string; required?: boolean }[];
}

interface PipelineComponent {
  type: 'SOFTWARE_LIBRARY' | 'CUSTOM_SCRIPT';
  name: string;
  componentArn?: string;
  script?: string;
  parameterValues?: { [paramName: string]: string };
}

interface BaseImage {
  id: string;
  name: string;
  platform: string;
  description?: string;
  createdAt?: string;
  isAutoGenerated?: boolean;
}

const BASE_IMAGE_OPTIONS: BaseImage[] = [
  { id: 'windows-2025', name: 'Windows Server 2025 Base', platform: 'Windows', description: 'Latest Windows Server', isAutoGenerated: true },
  { id: 'windows-2022', name: 'Windows Server 2022 Base', platform: 'Windows', description: 'Windows Server', isAutoGenerated: true },
  { id: 'windows-2019', name: 'Windows Server 2019 Base', platform: 'Windows', description: 'Windows Server', isAutoGenerated: true },
  { id: 'ubuntu-22.04', name: 'Ubuntu Server 22.04 LTS', platform: 'Linux', description: 'Ubuntu/Debian-based', isAutoGenerated: true },
  { id: 'rocky-8', name: 'Rocky Linux 8', platform: 'Linux', description: 'RHEL-compatible, required for DaVinci Resolve', isAutoGenerated: true },
  { id: 'rocky-9', name: 'Rocky Linux 9', platform: 'Linux', description: 'RHEL-compatible, latest Rocky Linux', isAutoGenerated: true },
];

interface ImageCreationAntdProps {
  user: any;
  isAdmin: boolean;
  config?: any;
  onSignOut: () => void;
  onChangePassword?: () => void;
}

const ImageCreationAntd: React.FC<ImageCreationAntdProps> = ({
  user,
  isAdmin,
  config,
  onSignOut,
  onChangePassword,
}) => {
  const navigate = useNavigate();
  const [currentStep, setCurrentStep] = useState(0);
  const [pipelineName, setPipelineName] = useState('');
  const [description, setDescription] = useState('');
  const [baseImageId, setBaseImageId] = useState('windows-2025');
  const [selectedComponents, setSelectedComponents] = useState<PipelineComponent[]>([]);
  const [softwareLibrary, setSoftwareLibrary] = useState<SoftwareComponent[]>([]);
  const [loadingSoftware, setLoadingSoftware] = useState(false);
  const [creating, setCreating] = useState(false);
  const [error, setError] = useState('');

  // Base image selection
  const [activePlatformTab, setActivePlatformTab] = useState('windows');
  const [macosImages, setMacosImages] = useState<BaseImage[]>([]);
  const [loadingMacosImages, setLoadingMacosImages] = useState(false);
  const [selectedBaseImage, setSelectedBaseImage] = useState<BaseImage | null>(
    BASE_IMAGE_OPTIONS.find((img) => img.id === 'windows-2025') || null
  );

  // Software selection
  const [selectedSoftwareIds, setSelectedSoftwareIds] = useState<string[]>([]);
  const selectedSoftwareIdsRef = useRef<string[]>([]);
  // Parameter values keyed by softwareId, then paramName
  const [componentParameterValues, setComponentParameterValues] = useState<{ [softwareId: string]: { [paramName: string]: string } }>({});
  const [softwareSearch, setSoftwareSearch] = useState('');

  // Custom script modal
  const [showCustomScriptModal, setShowCustomScriptModal] = useState(false);
  const [scriptName, setScriptName] = useState('');
  const [customScript, setCustomScript] = useState('');

  // Add software wizard modal (replaces old simple modal)
  const [showAddSoftwareWizard, setShowAddSoftwareWizard] = useState(false);
  const [isWizardGenerating, setIsWizardGenerating] = useState(false);

  // Ref for pipeline name input autofocus
  const pipelineNameRef = useRef<InputRef>(null);

  useEffect(() => {
    loadSoftwareLibrary();
    loadMacosImages();
  }, []);

  // Focus pipeline name input on page load
  useEffect(() => {
    const timer = setTimeout(() => {
      pipelineNameRef.current?.focus();
    }, 100);
    return () => clearTimeout(timer);
  }, []);

  const loadMacosImages = async () => {
    setLoadingMacosImages(true);
    try {
      const token = getAuthToken();
      if (!token) return;

      const response = await apiCall('/images', {
        method: 'GET',
        headers: { Authorization: `Bearer ${token}` },
      });

      if (response.ok) {
        const data = await response.json();
        const macosOnly = (data || [])
          .filter((img: any) => img.platform?.toLowerCase() === 'macos')
          .map((img: any) => ({
            id: img.amiId,
            name: img.name,
            platform: 'macOS',
            description: img.description,
            createdAt: img.createdAt,
            isAutoGenerated: false,
          }));
        setMacosImages(macosOnly);
      }
    } catch (error) {
      console.error('Failed to load macOS images:', error);
    } finally {
      setLoadingMacosImages(false);
    }
  };

  const loadSoftwareLibrary = async () => {
    setLoadingSoftware(true);
    try {
      const token = getAuthToken();
      if (!token) return;

      const response = await apiCall('/images/software', {
        method: 'GET',
        headers: { Authorization: `Bearer ${token}` },
      });

      if (response.ok) {
        const data = await response.json();
        setSoftwareLibrary(data.items || []);
      }
    } catch (error) {
      console.error('Failed to load software library:', error);
    } finally {
      setLoadingSoftware(false);
    }
  };

  const selectedPlatform = useMemo(() => {
    return selectedBaseImage?.platform || 'Windows';
  }, [selectedBaseImage]);

  const selectedInstanceType = useMemo(() => {
    if (selectedPlatform === 'macOS') return 'mac2.metal';
    const hasGpuSoftware = selectedComponents.some(
      (comp) =>
        comp.type === 'SOFTWARE_LIBRARY' &&
        softwareLibrary.find((sw) => sw.componentArn === comp.componentArn)?.gpuRequired === true
    );
    return hasGpuSoftware ? 'g4dn.xlarge' : 'm5.large';
  }, [selectedComponents, softwareLibrary, selectedPlatform]);

  const filteredSoftware = useMemo(() => {
    if (!Array.isArray(softwareLibrary)) return [];

    let filtered = softwareLibrary.filter((software) => {
      const softwarePlatform = software.platform || 'Windows';
      return softwarePlatform === selectedPlatform;
    });

    if (softwareSearch) {
      const search = softwareSearch.toLowerCase();
      filtered = filtered.filter(
        (sw) =>
          sw.name.toLowerCase().includes(search) ||
          sw.category?.toLowerCase().includes(search) ||
          sw.description?.toLowerCase().includes(search)
      );
    }

    return filtered;
  }, [softwareLibrary, selectedPlatform, softwareSearch]);

  useEffect(() => {
    if (selectedBaseImage) {
      setBaseImageId(selectedBaseImage.id);
    }
  }, [selectedBaseImage]);

  const addCustomScript = () => {
    if (scriptName && customScript) {
      const exists = selectedComponents.some(
        (comp) => comp.type === 'CUSTOM_SCRIPT' && comp.name === scriptName
      );
      if (exists) return;

      setSelectedComponents([
        ...selectedComponents,
        { type: 'CUSTOM_SCRIPT', name: scriptName, script: customScript },
      ]);
      setShowCustomScriptModal(false);
      setScriptName('');
      setCustomScript('');
    }
  };

  const removeComponent = (index: number) => {
    const newComponents = [...selectedComponents];
    newComponents.splice(index, 1);
    setSelectedComponents(newComponents);
  };

  const createPipeline = async () => {
    if (!pipelineName || !selectedBaseImage) {
      setError('Pipeline name and base image are required');
      return;
    }

    setCreating(true);
    setError('');

    try {
      const token = getAuthToken();
      if (!token) {
        setError('Authentication required');
        return;
      }

      const response = await apiCall('/images/create-pipeline', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify({
          name: pipelineName,
          description,
          baseImageId,
          platform: selectedPlatform,
          instanceType: selectedInstanceType,
          components: selectedComponents,
        }),
      });

      if (response.ok) {
        navigate('/pipelines');
      } else {
        const errorData = await response.json();
        setError(errorData.error || 'Failed to create pipeline');
      }
    } catch (error) {
      console.error('Error creating pipeline:', error);
      setError('Failed to create pipeline');
    } finally {
      setCreating(false);
    }
  };

  const syncSoftwareSelections = () => {
    const currentSelections = selectedSoftwareIdsRef.current;
    const selectedArns = new Set(
      currentSelections
        .map((id) => softwareLibrary.find((item) => item.softwareId === id)?.componentArn)
        .filter(Boolean)
    );

    setSelectedComponents((prev) => {
      const nonSoftware = prev.filter((comp) => comp.type !== 'SOFTWARE_LIBRARY');
      const selectedSoftware = currentSelections
        .map((id) => softwareLibrary.find((item) => item.softwareId === id))
        .filter(Boolean)
        .map((software) => ({
          type: 'SOFTWARE_LIBRARY' as const,
          name: `${software!.name}${software!.versionNumber ? ` v${software!.versionNumber}` : ''}`,
          componentArn: software!.componentArn,
          parameterValues: componentParameterValues[software!.softwareId] || undefined,
        }));
      return [...nonSoftware, ...selectedSoftware];
    });
  };

  const handleNext = () => {
    if (currentStep === 0 && !selectedBaseImage) {
      setError('Please select a base image');
      return;
    }
    if (currentStep === 0 && !pipelineName) {
      setError('Please enter a pipeline name');
      return;
    }
    if (currentStep === 1) {
      syncSoftwareSelections();
    }
    setError('');
    setCurrentStep(currentStep + 1);
  };

  const handlePrev = () => {
    if (currentStep === 2) {
      // Sync back when going to software step
      const softwareComponents = selectedComponents.filter((comp) => comp.type === 'SOFTWARE_LIBRARY');
      const ids = softwareComponents
        .map((comp) => softwareLibrary.find((item) => item.componentArn === comp.componentArn)?.softwareId)
        .filter(Boolean) as string[];
      setSelectedSoftwareIds(ids);
      selectedSoftwareIdsRef.current = ids;
    }
    setCurrentStep(currentStep - 1);
  };

  // Base image table columns
  const baseImageColumns: ColumnsType<BaseImage> = [
    { title: 'Name', dataIndex: 'name', key: 'name' },
    { title: 'Description', dataIndex: 'description', key: 'description', render: (d) => d || '-' },
  ];

  const macosImageColumns: ColumnsType<BaseImage> = [
    { title: 'Name', dataIndex: 'name', key: 'name' },
    {
      title: 'Created',
      dataIndex: 'createdAt',
      key: 'createdAt',
      render: (d) => (d ? new Date(d).toLocaleDateString() : '-'),
    },
  ];

  // Software table columns
  const softwareColumns: ColumnsType<SoftwareComponent> = [
    {
      title: 'Name',
      key: 'name',
      sorter: (a, b) => a.name.localeCompare(b.name),
      render: (_, record) => (
        <Space>
          <Text strong>{record.name}</Text>
          {record.versionNumber && <Text type="secondary">v{record.versionNumber}</Text>}
        </Space>
      ),
    },
    {
      title: 'Category',
      dataIndex: 'category',
      key: 'category',
      width: 120,
      sorter: (a, b) => (a.category || '').localeCompare(b.category || ''),
      render: (cat) => <Tag color="blue">{cat}</Tag>,
    },
    { title: 'Description', dataIndex: 'description', key: 'description', ellipsis: true },
    {
      title: 'Install Time',
      dataIndex: 'estimatedInstallTime',
      key: 'estimatedInstallTime',
      width: 120,
      sorter: (a, b) => {
        // Parse install time strings like "5-10 minutes", "1-2 minutes"
        const parseTime = (str: string | undefined) => {
          if (!str) return 0;
          const match = str.match(/(\d+)/);
          return match ? parseInt(match[1], 10) : 0;
        };
        return parseTime(a.estimatedInstallTime) - parseTime(b.estimatedInstallTime);
      },
    },
    {
      title: 'Disk Space',
      dataIndex: 'diskSpaceRequired',
      key: 'diskSpaceRequired',
      width: 100,
      sorter: (a, b) => {
        // Parse disk space strings like "500 MB", "3.5 GB"
        const parseSize = (str: string | undefined) => {
          if (!str) return 0;
          const match = str.match(/([\d.]+)\s*(MB|GB|TB)/i);
          if (!match) return 0;
          const value = parseFloat(match[1]);
          const unit = match[2].toUpperCase();
          if (unit === 'GB') return value * 1024;
          if (unit === 'TB') return value * 1024 * 1024;
          return value; // MB
        };
        return parseSize(a.diskSpaceRequired) - parseSize(b.diskSpaceRequired);
      },
    },
  ];

  const steps = [
    { title: 'Configuration' },
    { title: 'Software' },
    { title: 'Scripts' },
    { title: 'Review' },
  ];

  // Step 1: Pipeline Configuration
  const renderConfigurationStep = () => (
    <Space direction="vertical" size={24} style={{ width: '100%' }}>
      <div>
        <Text strong style={{ display: 'block', marginBottom: 8 }}>Pipeline Name *</Text>
        <Input
          ref={pipelineNameRef}
          value={pipelineName}
          onChange={(e) => setPipelineName(e.target.value)}
          placeholder="e.g., Media Workstation Pipeline"
          style={{ maxWidth: 500 }}
        />
        <Text type="secondary" style={{ display: 'block', marginTop: 4 }}>
          Enter a descriptive name for this pipeline
        </Text>
      </div>

      <div>
        <Text strong style={{ display: 'block', marginBottom: 8 }}>Description</Text>
        <TextArea
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          placeholder="Describe what this image will be used for..."
          rows={3}
          style={{ maxWidth: 500 }}
        />
      </div>

      <div>
        <Text strong style={{ display: 'block', marginBottom: 8 }}>Base Image *</Text>
        <Text type="secondary" style={{ display: 'block', marginBottom: 12 }}>
          Select the operating system for your image pipeline
        </Text>
        <Tabs
          activeKey={activePlatformTab}
          onChange={(key) => {
            setActivePlatformTab(key);
            setSelectedBaseImage(null);
            // Clear software when switching platforms
            setSelectedSoftwareIds([]);
            selectedSoftwareIdsRef.current = [];
            setSelectedComponents((prev) => prev.filter((c) => c.type !== 'SOFTWARE_LIBRARY'));
          }}
          items={[
            {
              key: 'windows',
              label: 'Windows',
              children: (
                <Table
                  rowKey="id"
                  columns={baseImageColumns}
                  dataSource={BASE_IMAGE_OPTIONS.filter((img) => img.platform === 'Windows')}
                  pagination={false}
                  size="small"
                  rowSelection={{
                    type: 'radio',
                    selectedRowKeys: selectedBaseImage?.platform === 'Windows' ? [selectedBaseImage.id] : [],
                    onChange: (_, rows) => setSelectedBaseImage(rows[0] || null),
                  }}
                />
              ),
            },
            {
              key: 'linux',
              label: 'Linux',
              children: (
                <Table
                  rowKey="id"
                  columns={baseImageColumns}
                  dataSource={BASE_IMAGE_OPTIONS.filter((img) => img.platform === 'Linux')}
                  pagination={false}
                  size="small"
                  rowSelection={{
                    type: 'radio',
                    selectedRowKeys: selectedBaseImage?.platform === 'Linux' ? [selectedBaseImage.id] : [],
                    onChange: (_, rows) => setSelectedBaseImage(rows[0] || null),
                  }}
                />
              ),
            },
            {
              key: 'macos',
              label: 'macOS',
              children: (
                <Space direction="vertical" size={12} style={{ width: '100%' }}>
                  {macosImages.length === 0 && !loadingMacosImages && (
                    <Alert
                      type="info"
                      message="No macOS base images available. macOS pipelines require a DCV-Ready base image. Build one of the system pipelines first."
                    />
                  )}
                  <Table
                    rowKey="id"
                    columns={macosImageColumns}
                    dataSource={macosImages}
                    loading={loadingMacosImages}
                    pagination={false}
                    size="small"
                    rowSelection={{
                      type: 'radio',
                      selectedRowKeys: selectedBaseImage?.platform === 'macOS' ? [selectedBaseImage.id] : [],
                      onChange: (_, rows) => setSelectedBaseImage(rows[0] || null),
                    }}
                    locale={{ emptyText: 'No macOS base images available' }}
                  />
                </Space>
              ),
            },
          ]}
        />
      </div>
    </Space>
  );

  // Step 2: Software Components
  const renderSoftwareStep = () => (
    <Space direction="vertical" size={16} style={{ width: '100%' }}>
      <Alert
        type="info"
        message={`Showing ${selectedPlatform} software components only. Change the base image in the previous step to see other platforms.`}
      />

      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Text strong>Available Software ({filteredSoftware.length})</Text>
        <Space>
          <Button icon={<ReloadOutlined />} onClick={loadSoftwareLibrary} loading={loadingSoftware} />
          <Button onClick={() => navigate('/software')}>Manage Library</Button>
          <Button type="primary" icon={<PlusOutlined />} onClick={() => setShowAddSoftwareWizard(true)}>
            Add Software
          </Button>
        </Space>
      </div>

      <Input.Search
        placeholder="Search software by name, category, or description"
        value={softwareSearch}
        onChange={(e) => setSoftwareSearch(e.target.value)}
        allowClear
        style={{ maxWidth: 400 }}
      />

      <Table
        rowKey="softwareId"
        columns={softwareColumns}
        dataSource={filteredSoftware}
        loading={loadingSoftware}
        pagination={{ pageSize: 10 }}
        size="small"
        rowSelection={{
          selectedRowKeys: selectedSoftwareIds,
          onChange: (keys) => {
            setSelectedSoftwareIds(keys as string[]);
            selectedSoftwareIdsRef.current = keys as string[];
          },
        }}
        locale={{ emptyText: 'No software components available for this platform' }}
      />

      {/* Parameter inputs for selected components */}
      {selectedSoftwareIds.length > 0 && (() => {
        const selectedWithParams = selectedSoftwareIds
          .map(id => softwareLibrary.find(item => item.softwareId === id))
          .filter(sw => sw && sw.parameters && sw.parameters.length > 0);
        if (selectedWithParams.length === 0) return null;
        return (
          <Card title="Component Parameters" size="small">
            <Space direction="vertical" size={16} style={{ width: '100%' }}>
              {selectedWithParams.map(software => (
                <div key={software!.softwareId}>
                  <Text strong style={{ display: 'block', marginBottom: 8 }}>{software!.name}</Text>
                  <Row gutter={[16, 12]}>
                    {software!.parameters!.map(param => (
                      <Col span={12} key={param.name}>
                        <div style={{ marginBottom: 4 }}>
                          <Text>{param.name}</Text>
                          {param.required && <Text type="danger"> *</Text>}
                          {param.description && (
                            <Text type="secondary" style={{ display: 'block', fontSize: 12 }}>{param.description}</Text>
                          )}
                        </div>
                        <Input
                          value={componentParameterValues[software!.softwareId]?.[param.name] || ''}
                          onChange={(e) => {
                            setComponentParameterValues(prev => ({
                              ...prev,
                              [software!.softwareId]: {
                                ...prev[software!.softwareId],
                                [param.name]: e.target.value
                              }
                            }));
                          }}
                          placeholder={`Enter ${param.name}`}
                        />
                      </Col>
                    ))}
                  </Row>
                </div>
              ))}
            </Space>
          </Card>
        );
      })()}
    </Space>
  );

  // Step 3: Custom Scripts
  const renderScriptsStep = () => {
    const customScripts = selectedComponents.filter((comp) => comp.type === 'CUSTOM_SCRIPT');

    return (
      <Space direction="vertical" size={16} style={{ width: '100%' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <Text strong>Custom Installation Scripts</Text>
          <Button type="primary" icon={<CodeOutlined />} onClick={() => setShowCustomScriptModal(true)}>
            Add Custom Script
          </Button>
        </div>

        {customScripts.length === 0 ? (
          <Empty
            description={
              <span>
                No custom scripts added.
                <br />
                Add custom {selectedPlatform === 'Linux' ? 'Bash' : 'PowerShell'} scripts for specialized
                installation tasks.
              </span>
            }
          />
        ) : (
          <Space direction="vertical" size={8} style={{ width: '100%' }}>
            {customScripts.map((comp, idx) => {
              const realIndex = selectedComponents.indexOf(comp);
              return (
                <Card key={idx} size="small" >
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <Space>
                      <CodeOutlined />
                      <Text strong>{comp.name}</Text>
                      <Tag color="blue">Custom Script</Tag>
                    </Space>
                    <Button
                      type="text"
                      danger
                      icon={<DeleteOutlined />}
                      onClick={() => removeComponent(realIndex)}
                    >
                      Remove
                    </Button>
                  </div>
                </Card>
              );
            })}
          </Space>
        )}
      </Space>
    );
  };

  // Step 4: Review
  const renderReviewStep = () => (
    <Space direction="vertical" size={24} style={{ width: '100%' }}>
      <div>
        <Text strong style={{ fontSize: 14, display: 'block', marginBottom: 12 }}>Pipeline Configuration</Text>
        <Descriptions column={{ xs: 1, sm: 2 }} size="small">
          <Descriptions.Item label="Name">{pipelineName}</Descriptions.Item>
          <Descriptions.Item label="Description">{description || 'None'}</Descriptions.Item>
          <Descriptions.Item label="Base Image">{selectedBaseImage?.name}</Descriptions.Item>
          <Descriptions.Item label="Platform">{selectedPlatform}</Descriptions.Item>
          <Descriptions.Item label="Instance Type">
            {selectedInstanceType}
            {selectedInstanceType === 'mac2.metal' && ' (macOS Dedicated Host)'}
            {selectedInstanceType === 'g4dn.xlarge' && ' (GPU - Auto-selected)'}
            {selectedInstanceType === 'm5.large' && ' (Standard)'}
          </Descriptions.Item>
        </Descriptions>
      </div>

      <Divider style={{ margin: 0 }} />

      <div>
        <Text strong style={{ fontSize: 14, display: 'block', marginBottom: 12 }}>
          Selected Components ({selectedComponents.length})
        </Text>
        {selectedComponents.length === 0 ? (
          <Text type="secondary">No components selected</Text>
        ) : (
          <Space direction="vertical" size={8} style={{ width: '100%' }}>
            {selectedComponents.map((comp, idx) => (
              <div key={idx} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                <Text>{comp.name}</Text>
                <Tag color={comp.type === 'CUSTOM_SCRIPT' ? 'blue' : 'green'}>{comp.type.replace('_', ' ')}</Tag>
              </div>
            ))}
          </Space>
        )}
      </div>
    </Space>
  );

  const renderStepContent = () => {
    switch (currentStep) {
      case 0:
        return renderConfigurationStep();
      case 1:
        return renderSoftwareStep();
      case 2:
        return renderScriptsStep();
      case 3:
        return renderReviewStep();
      default:
        return null;
    }
  };

  return (
    <AppLayoutAntd
      isAdmin={isAdmin}
      user={user}
      config={config}
      onSignOut={onSignOut}
      onChangePassword={onChangePassword}
    >
      <div style={{ width: '100%' }}>
        {/* Breadcrumb */}
        <Breadcrumb
          style={{ marginBottom: 16 }}
          items={[
            { href: '/dashboard', title: <><HomeOutlined /> Dashboard</> },
            { href: '/pipelines', title: 'Pipelines' },
            { title: 'Create Pipeline' },
          ]}
        />

        {/* Header */}
        <div style={{ marginBottom: 24 }}>
          <Title level={3} style={{ margin: 0 }}>Create Image Pipeline</Title>
          <Text type="secondary">
            Create custom AMIs using EC2 Image Builder. Configure your base image, add software components, and
            define build settings.
          </Text>
        </div>

        {error && (
          <Alert
            type="error"
            message={error}
            closable
            onClose={() => setError('')}
            style={{ marginBottom: 16 }}
          />
        )}

        {/* Wizard Card */}
        <Card >
          <Steps current={currentStep} items={steps} style={{ marginBottom: 32 }} />

          <div style={{ minHeight: 400 }}>{renderStepContent()}</div>

          <Divider />

          <div style={{ display: 'flex', justifyContent: 'space-between' }}>
            <Button onClick={() => navigate('/pipelines')}>Cancel</Button>
            <Space>
              {currentStep > 0 && <Button onClick={handlePrev}>Previous</Button>}
              {currentStep < steps.length - 1 && (
                <Button type="primary" onClick={handleNext}>
                  Next
                </Button>
              )}
              {currentStep === steps.length - 1 && (
                <Button type="primary" onClick={createPipeline} loading={creating}>
                  Create Pipeline
                </Button>
              )}
            </Space>
          </div>
        </Card>

        {/* Custom Script Modal */}
        <Modal
          title="Add Custom Script"
          open={showCustomScriptModal}
          onCancel={() => setShowCustomScriptModal(false)}
          onOk={addCustomScript}
          okText="Add Script"
        >
          <Space direction="vertical" size={16} style={{ width: '100%' }}>
            <div>
              <Text strong style={{ display: 'block', marginBottom: 4 }}>Script Name</Text>
              <Input
                value={scriptName}
                onChange={(e) => setScriptName(e.target.value)}
                placeholder="e.g., Configure System Settings"
              />
            </div>
            <div>
              <Text strong style={{ display: 'block', marginBottom: 4 }}>
                {selectedPlatform === 'Linux' ? 'Bash Script' : 'PowerShell Script'}
              </Text>
              <TextArea
                value={customScript}
                onChange={(e) => setCustomScript(e.target.value)}
                placeholder={
                  selectedPlatform === 'Linux'
                    ? '#!/bin/bash\n# Enter your Bash script here...'
                    : '# Enter your PowerShell script here...'
                }
                rows={10}
                style={{ fontFamily: 'monospace' }}
              />
            </div>
          </Space>
        </Modal>

        {/* Add Software Wizard Modal */}
        <Modal
          title="Add Software to Library"
          open={showAddSoftwareWizard}
          onCancel={() => {
            if (!isWizardGenerating) {
              setShowAddSoftwareWizard(false);
            }
          }}
          footer={null}
          width={800}
          maskClosable={!isWizardGenerating}
          destroyOnClose
        >
          <AddSoftwareWizardAntd
            onComplete={() => {
              setShowAddSoftwareWizard(false);
              setIsWizardGenerating(false);
              loadSoftwareLibrary();
            }}
            onCancel={() => {
              setShowAddSoftwareWizard(false);
              setIsWizardGenerating(false);
            }}
            onGeneratingChange={setIsWizardGenerating}
          />
        </Modal>
      </div>
    </AppLayoutAntd>
  );
};

export default ImageCreationAntd;
