// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import React, { useState, useEffect, useMemo } from 'react';
import {
  Card,
  Table,
  Button,
  Modal,
  Form,
  Input,
  Select,
  Alert,
  Tag,
  Space,
  Typography,
  Breadcrumb,
  Tooltip,
  Tabs,
} from 'antd';
import {
  PlusOutlined,
  DeleteOutlined,
  ReloadOutlined,
  HomeOutlined,
  EditOutlined,
  DesktopOutlined,
  DownOutlined,
  RightOutlined,
  CopyOutlined,
  GlobalOutlined,
} from '@ant-design/icons';
import type { ColumnsType } from 'antd/es/table';
import AppLayoutAntd from '../components/AppLayoutAntd';
import { getAuthToken } from '../utils/auth';
import { apiCall } from '../utils/api';

const { Title, Text, Link } = Typography;
const { TextArea } = Input;

interface AMIImage {
  amiId: string;
  name: string;
  platform: string;
  description?: string;
  owner?: string;
  state?: string;
  visibility?: string;
  architecture?: string;
  virtualizationType?: string;
  createdAt?: string;
  updatedAt?: string;
  isAutoGenerated?: boolean;
  requiresPipeline?: boolean;
  requiresPipelineReason?: string;
  pipelineId?: string;
  region?: string;
  sourceRegion?: string;
}

interface GroupedImage {
  id: string;
  name: string;
  platform: string;
  description?: string;
  state?: string;
  createdAt?: string;
  isAutoGenerated?: boolean;
  requiresPipeline?: boolean;
  pipelineId?: string;
  type: string;
  regions: Array<{ region: string; amiId: string }>;
  amiId?: string;
  region?: string;
}

interface ImageManagementAntdProps {
  user: any;
  isAdmin: boolean;
  config?: any;
  onSignOut: () => void;
  onChangePassword?: () => void;
}

const platformOptions = [
  { label: 'Windows', value: 'windows' },
  { label: 'Linux', value: 'linux' },
  { label: 'macOS', value: 'macos' },
];

const typeFilterOptions = [
  { label: 'All Types', value: '' },
  { label: 'Base Image', value: 'Base Image' },
  { label: 'Pipeline', value: 'Pipeline' },
  { label: 'Imported', value: 'Imported' },
];

const platformFilterOptions = [
  { label: 'All Platforms', value: '' },
  { label: 'Windows', value: 'windows' },
  { label: 'Linux', value: 'linux' },
  { label: 'macOS', value: 'macos' },
];

const isValidAmiId = (amiId: string): boolean => {
  return /^ami-[a-f0-9]{8,17}$/.test(amiId);
};

const ImageManagementAntd: React.FC<ImageManagementAntdProps> = ({
  user,
  isAdmin,
  config,
  onSignOut,
  onChangePassword,
}) => {
  const [images, setImages] = useState<AMIImage[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedRowKeys, setSelectedRowKeys] = useState<React.Key[]>([]);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [showCopyModal, setShowCopyModal] = useState(false);
  const [editingImage, setEditingImage] = useState<GroupedImage | null>(null);
  const [deleting, setDeleting] = useState(false);
  const [creating, setCreating] = useState(false);
  const [copying, setCopying] = useState(false);
  const [alert, setAlert] = useState<{ type: 'success' | 'error' | 'info' | 'warning'; message: string } | null>(null);
  const [expandedRowKeys, setExpandedRowKeys] = useState<React.Key[]>([]);
  const [filterText, setFilterText] = useState('');
  const [typeFilter, setTypeFilter] = useState('');
  const [platformFilter, setPlatformFilter] = useState('');
  const [regionalHubs, setRegionalHubs] = useState<any[]>([]);
  const [selectedCopyRegions, setSelectedCopyRegions] = useState<string[]>([]);

  // Table preferences with localStorage persistence
  const [sortedInfo, setSortedInfo] = useState<{ columnKey: string; order: 'ascend' | 'descend' } | null>(() => {
    try {
      const saved = localStorage.getItem('images-table-sort');
      if (saved) return JSON.parse(saved);
    } catch (e) {}
    return { columnKey: 'name', order: 'ascend' };
  });

  const [pageSize, setPageSize] = useState(() => {
    try {
      const saved = localStorage.getItem('images-table-pageSize');
      if (saved) return parseInt(saved, 10);
    } catch (e) {}
    return 10;
  });

  const [form] = Form.useForm();
  const [editForm] = Form.useForm();

  useEffect(() => {
    fetchImages();
    fetchRegionalHubs();
  }, []);

  const fetchRegionalHubs = async () => {
    try {
      const token = getAuthToken();
      if (!token) return;
      const response = await apiCall('regions', {
        headers: { Authorization: `Bearer ${token}` },
      });
      if (response.ok) {
        const responseData = await response.json();
        const hubs = responseData.data || responseData;
        const availableHubs = (Array.isArray(hubs) ? hubs : []).filter(
          (hub: any) => hub.status === 'available' || hub.isPrimary
        );
        setRegionalHubs(availableHubs);
      }
    } catch (error) {
      console.log('Could not fetch regional hubs:', error);
    }
  };

  const fetchImages = async () => {
    try {
      setLoading(true);
      const token = getAuthToken();
      if (!token) throw new Error('No current user');

      const response = await apiCall('images', {
        headers: { 'Authorization': `Bearer ${token}` },
      });

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`);
      }

      const data = await response.json();
      setImages(Array.isArray(data) ? data : []);
    } catch (error) {
      console.error('Error fetching images:', error);
      setAlert({ type: 'error', message: `Failed to fetch images: ${(error as Error).message}` });
      setImages([]);
    } finally {
      setLoading(false);
    }
  };

  // Group images by pipelineId AND name
  const groupedImages = useMemo((): GroupedImage[] => {
    if (!Array.isArray(images)) return [];

    const buildGroups = new Map<string, AMIImage[]>();
    const standaloneImages: AMIImage[] = [];

    images.forEach((image) => {
      if (image.pipelineId) {
        const groupKey = `${image.pipelineId}::${image.name}`;
        const existing = buildGroups.get(groupKey) || [];
        existing.push(image);
        buildGroups.set(groupKey, existing);
      } else {
        standaloneImages.push(image);
      }
    });

    const result: GroupedImage[] = [];

    buildGroups.forEach((buildImages, groupKey) => {
      const sortedImages = [...buildImages].sort((a, b) => {
        if (!a.sourceRegion && b.sourceRegion) return -1;
        if (a.sourceRegion && !b.sourceRegion) return 1;
        return (a.region || '').localeCompare(b.region || '');
      });

      const primaryImage = sortedImages[0];

      result.push({
        id: groupKey,
        name: primaryImage.name,
        platform: primaryImage.platform,
        description: primaryImage.description?.replace(/\s*\(distributed to [^)]+\)/, '') || '',
        state: primaryImage.state,
        createdAt: primaryImage.createdAt,
        isAutoGenerated: primaryImage.isAutoGenerated,
        requiresPipeline: primaryImage.requiresPipeline,
        pipelineId: primaryImage.pipelineId,
        type: primaryImage.isAutoGenerated ? 'Base Image' : 'Pipeline',
        regions: sortedImages.map((img) => ({
          region: img.region || '',
          amiId: img.amiId,
        })),
      });
    });

    standaloneImages.forEach((image) => {
      result.push({
        id: image.amiId,
        name: image.name,
        platform: image.platform,
        description: image.description,
        state: image.state,
        createdAt: image.createdAt,
        isAutoGenerated: image.isAutoGenerated,
        requiresPipeline: image.requiresPipeline,
        amiId: image.amiId,
        region: image.region,
        type: image.isAutoGenerated ? 'Base Image' : 'Imported',
        regions: [{ region: image.region || '', amiId: image.amiId }],
      });
    });

    return result;
  }, [images]);

  // Filter images
  const filteredImages = useMemo(() => {
    let filtered = [...groupedImages];

    if (filterText) {
      const searchText = filterText.toLowerCase();
      filtered = filtered.filter(
        (image) =>
          image.name?.toLowerCase().includes(searchText) ||
          image.platform?.toLowerCase().includes(searchText) ||
          image.regions?.some((r) => r.amiId?.toLowerCase().includes(searchText))
      );
    }

    if (typeFilter) {
      filtered = filtered.filter((image) => image.type === typeFilter);
    }

    if (platformFilter) {
      filtered = filtered.filter((image) => image.platform?.toLowerCase() === platformFilter.toLowerCase());
    }

    return filtered;
  }, [groupedImages, filterText, typeFilter, platformFilter]);

  const selectedImages = useMemo(() => {
    return groupedImages.filter((img) => selectedRowKeys.includes(img.id));
  }, [groupedImages, selectedRowKeys]);

  const handleTableChange = (pagination: any, filters: any, sorter: any) => {
    const newSort = sorter.order 
      ? { columnKey: sorter.columnKey || sorter.field, order: sorter.order }
      : null;
    setSortedInfo(newSort);
    try {
      if (newSort) {
        localStorage.setItem('images-table-sort', JSON.stringify(newSort));
      } else {
        localStorage.removeItem('images-table-sort');
      }
    } catch (e) {}
  };

  const handlePageSizeChange = (current: number, size: number) => {
    setPageSize(size);
    try {
      localStorage.setItem('images-table-pageSize', String(size));
    } catch (e) {}
  };

  const handleCreateImage = async () => {
    try {
      const values = await form.validateFields();

      if (!isValidAmiId(values.amiId)) {
        setAlert({
          type: 'error',
          message: 'Invalid AMI ID format. Must start with "ami-" followed by 8-17 hex characters.',
        });
        return;
      }

      setCreating(true);
      const token = getAuthToken();
      if (!token) throw new Error('No current user');

      const response = await apiCall('images', {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(values),
      });

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`API Error: ${response.status} - ${errorText}`);
      }

      setAlert({ type: 'success', message: 'Image imported successfully' });
      setShowCreateModal(false);
      form.resetFields();
      fetchImages();
    } catch (error) {
      console.error('Error creating image:', error);
      setAlert({ type: 'error', message: `Failed to import image: ${(error as Error).message}` });
    } finally {
      setCreating(false);
    }
  };

  const handleEditClick = () => {
    if (selectedRowKeys.length !== 1) return;
    const image = selectedImages[0];

    if (image.isAutoGenerated) {
      setAlert({
        type: 'error',
        message: 'Cannot edit auto-generated AMI. This AMI is automatically managed by AWS.',
      });
      return;
    }

    setEditingImage(image);
    editForm.setFieldsValue({
      amiId: image.amiId || image.regions[0]?.amiId || '',
      name: image.name,
      platform: image.platform,
      description: image.description || '',
    });
    setShowEditModal(true);
  };

  const handleUpdateImage = async () => {
    if (!editingImage) return;

    try {
      const values = await editForm.validateFields();
      const token = getAuthToken();
      if (!token) throw new Error('No current user');

      const amiId = editingImage.amiId || editingImage.regions[0]?.amiId;

      await apiCall(`images/${amiId}`, {
        method: 'PUT',
        headers: {
          Authorization: `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          name: values.name,
          platform: values.platform,
          description: values.description,
        }),
      });

      setAlert({ type: 'success', message: 'Image updated successfully' });
      setShowEditModal(false);
      setEditingImage(null);
      setSelectedRowKeys([]);
      fetchImages();
    } catch (error) {
      console.error('Error updating image:', error);
      setAlert({ type: 'error', message: 'Failed to update image' });
    }
  };

  const handleDeleteImages = async () => {
    if (selectedImages.length === 0) return;

    // Check for auto-generated images
    const autoGeneratedItems = selectedImages.filter((item) => item.isAutoGenerated);
    if (autoGeneratedItems.length > 0) {
      setAlert({
        type: 'error',
        message: `Cannot delete auto-generated AMI${autoGeneratedItems.length > 1 ? 's' : ''}. These AMIs are automatically managed by AWS.`,
      });
      return;
    }

    setDeleting(true);
    try {
      const token = getAuthToken();
      if (!token) throw new Error('No current user');

      const deletePromises: Promise<Response>[] = [];
      selectedImages.forEach((image) => {
        image.regions.forEach((r) => {
          deletePromises.push(
            apiCall(`images/${r.amiId}`, {
              method: 'DELETE',
              headers: { Authorization: `Bearer ${token}` },
            })
          );
        });
      });

      await Promise.all(deletePromises);

      setAlert({ type: 'success', message: `${selectedImages.length} image(s) removed from management successfully` });
      setSelectedRowKeys([]);
      setShowDeleteModal(false);
      fetchImages();
    } catch (error) {
      console.error('Error deleting images:', error);
      setAlert({ type: 'error', message: 'Failed to remove images from management' });
    } finally {
      setDeleting(false);
    }
  };

  const handleCopyClick = () => {
    if (selectedImages.length !== 1) return;
    const image = selectedImages[0];

    if (image.isAutoGenerated) {
      setAlert({
        type: 'info',
        message: 'Auto-generated AMIs are automatically available in all regions.',
      });
      return;
    }

    // Get regions where the image already exists
    const existingRegions = image.regions.map((r) => r.region).filter(Boolean);
    
    // Filter out regions where the image already exists
    const availableRegions = regionalHubs
      .filter((hub) => !existingRegions.includes(hub.region))
      .map((hub) => hub.region);

    if (availableRegions.length === 0) {
      setAlert({
        type: 'info',
        message: 'This image is already available in all configured regions.',
      });
      return;
    }

    setSelectedCopyRegions([]);
    setShowCopyModal(true);
  };

  const handleCopyToRegions = async () => {
    if (selectedImages.length !== 1 || selectedCopyRegions.length === 0) return;
    const image = selectedImages[0];

    setCopying(true);
    try {
      const token = getAuthToken();
      if (!token) throw new Error('No current user');

      // Get the source AMI ID (first region's AMI)
      const sourceAmiId = image.amiId || image.regions[0]?.amiId;
      const sourceRegion = image.region || image.regions[0]?.region;

      const response = await apiCall('images/copy', {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          sourceAmiId,
          sourceRegion,
          targetRegions: selectedCopyRegions,
          name: image.name,
          platform: image.platform,
          description: image.description,
          pipelineId: image.pipelineId,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.error || errorData.message || 'Failed to copy image');
      }

      const result = await response.json();
      setAlert({ 
        type: 'success', 
        message: `Image copy initiated to ${selectedCopyRegions.length} region(s). This may take several minutes to complete.` 
      });
      setShowCopyModal(false);
      setSelectedRowKeys([]);
      
      // Refresh images after a delay to show the new copies
      setTimeout(() => fetchImages(), 3000);
    } catch (error) {
      console.error('Error copying image:', error);
      setAlert({ type: 'error', message: `Failed to copy image: ${(error as Error).message}` });
    } finally {
      setCopying(false);
    }
  };

  const getAvailableCopyRegions = () => {
    if (selectedImages.length !== 1) return [];
    const image = selectedImages[0];
    const existingRegions = image.regions.map((r) => r.region).filter(Boolean);
    return regionalHubs.filter((hub) => !existingRegions.includes(hub.region));
  };

  const handleCreateWorkstation = () => {
    if (selectedImages.length !== 1) return;
    const image = selectedImages[0];

    if (image.requiresPipeline) {
      setAlert({
        type: 'error',
        message: 'This image requires pipeline processing before it can be used to create workstations.',
      });
      return;
    }

    if (image.pipelineId && image.regions.length > 1) {
      window.location.href = `/workstations?create=true&pipelineId=${encodeURIComponent(image.id)}`;
    } else {
      const amiId = image.amiId || image.regions[0]?.amiId;
      window.location.href = `/workstations?create=true&imageId=${encodeURIComponent(amiId)}`;
    }
  };

  const getPlatformColor = (platform: string) => {
    switch (platform?.toLowerCase()) {
      case 'windows':
        return 'blue';
      case 'linux':
        return 'green';
      case 'macos':
        return 'default';
      default:
        return 'default';
    }
  };

  const getTypeColor = (type: string) => {
    switch (type) {
      case 'Base Image':
        return 'default';
      case 'Pipeline':
        return 'blue';
      case 'Imported':
        return 'green';
      default:
        return 'default';
    }
  };

  const columns: ColumnsType<GroupedImage> = [
    {
      title: 'Name',
      dataIndex: 'name',
      key: 'name',
      sorter: (a, b) => a.name.localeCompare(b.name),
      sortOrder: sortedInfo?.columnKey === 'name' ? sortedInfo.order : null,
      render: (text, record) => (
        <Space>
          <span>{text}</span>
          {record.requiresPipeline && <Tag color="red">Pipeline Required</Tag>}
        </Space>
      ),
    },
    {
      title: 'Platform',
      dataIndex: 'platform',
      key: 'platform',
      sorter: (a, b) => (a.platform || '').localeCompare(b.platform || ''),
      sortOrder: sortedInfo?.columnKey === 'platform' ? sortedInfo.order : null,
      render: (platform) => (
        <Tag color={getPlatformColor(platform)}>
          {platform ? platform.charAt(0).toUpperCase() + platform.slice(1) : 'Unknown'}
        </Tag>
      ),
    },
    {
      title: 'Regions',
      key: 'regions',
      render: (_, record) => {
        const validRegions = record.regions.filter((r) => r.region);
        if (validRegions.length === 0) return <Text type="secondary">-</Text>;
        if (validRegions.length === 1) {
          return (
            <span>
              {validRegions[0].region}{' '}
              <Text type="secondary">({validRegions[0].amiId})</Text>
            </span>
          );
        }
        return <Text>{validRegions.length} regions</Text>;
      },
    },
    {
      title: 'Type',
      dataIndex: 'type',
      key: 'type',
      sorter: (a, b) => a.type.localeCompare(b.type),
      sortOrder: sortedInfo?.columnKey === 'type' ? sortedInfo.order : null,
      render: (type) => <Tag color={getTypeColor(type)}>{type}</Tag>,
    },
    {
      title: 'State',
      dataIndex: 'state',
      key: 'state',
      sorter: (a, b) => (a.state || '').localeCompare(b.state || ''),
      sortOrder: sortedInfo?.columnKey === 'state' ? sortedInfo.order : null,
      render: (state) => (state ? state.charAt(0).toUpperCase() + state.slice(1).toLowerCase() : '-'),
    },
    {
      title: 'Created',
      dataIndex: 'createdAt',
      key: 'createdAt',
      sorter: (a, b) => (a.createdAt || '').localeCompare(b.createdAt || ''),
      sortOrder: sortedInfo?.columnKey === 'createdAt' ? sortedInfo.order : null,
      render: (date) => (date ? new Date(date).toLocaleDateString() : '-'),
    },
  ];

  // Expandable row for multi-region images
  const expandedRowRender = (record: GroupedImage) => {
    const validRegions = record.regions.filter((r) => r.region);
    if (validRegions.length <= 1) return null;

    return (
      <Table
        size="small"
        pagination={false}
        columns={[
          { title: 'Region', dataIndex: 'region', key: 'region' },
          { title: 'AMI ID', dataIndex: 'amiId', key: 'amiId' },
        ]}
        dataSource={validRegions.map((r, idx) => ({ key: idx, ...r }))}
      />
    );
  };

  return (
    <AppLayoutAntd
      isAdmin={isAdmin}
      user={user}
      config={config}
      onSignOut={onSignOut}
      onChangePassword={onChangePassword}
    >
      <div style={{ width: '100%' }}>
        {/* Breadcrumb */}
        <Breadcrumb
          style={{ marginBottom: 16 }}
          items={[
            { href: '/dashboard', title: <><HomeOutlined /> Dashboard</> },
            { title: 'Image Builder' },
            { title: 'Images' },
          ]}
        />

        {/* Header with title and actions */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
          <Title level={3} style={{ margin: 0 }}>Images</Title>
          <Space>
            <Tooltip title="Refresh">
              <Button icon={<ReloadOutlined />} onClick={fetchImages} loading={loading} />
            </Tooltip>
            <Button
              icon={<EditOutlined />}
              onClick={handleEditClick}
              disabled={selectedRowKeys.length !== 1}
            >
              Edit
            </Button>
            <Button
              icon={<DeleteOutlined />}
              onClick={() => {
                const autoGeneratedItems = selectedImages.filter((item) => item.isAutoGenerated);
                if (autoGeneratedItems.length > 0) {
                  setAlert({
                    type: 'error',
                    message: `Cannot delete auto-generated AMI${autoGeneratedItems.length > 1 ? 's' : ''}. These AMIs are automatically managed by AWS.`,
                  });
                  return;
                }
                setShowDeleteModal(true);
              }}
              disabled={selectedRowKeys.length === 0}
            >
              Remove
            </Button>
            <Button
              icon={<DesktopOutlined />}
              onClick={handleCreateWorkstation}
              disabled={selectedRowKeys.length !== 1}
            >
              Create Workstation
            </Button>
            {regionalHubs.length > 1 && (
              <Tooltip title="Copy image to other regions">
                <Button
                  icon={<GlobalOutlined />}
                  onClick={handleCopyClick}
                  disabled={selectedRowKeys.length !== 1}
                >
                  Copy to Region
                </Button>
              </Tooltip>
            )}
            <Button type="primary" icon={<PlusOutlined />} onClick={() => setShowCreateModal(true)}>
              Import Image
            </Button>
          </Space>
        </div>

        {alert && (
          <Alert
            type={alert.type}
            message={alert.message}
            closable
            onClose={() => setAlert(null)}
            style={{ marginBottom: 16 }}
          />
        )}

        <Card >
          {/* Filters */}
          <Space style={{ marginBottom: 16 }}>
            <Input.Search
              placeholder="Search by name or AMI ID"
              allowClear
              value={filterText}
              onChange={(e) => setFilterText(e.target.value)}
              style={{ width: 250 }}
            />
            <Select
              placeholder="Type"
              allowClear
              value={typeFilter || undefined}
              onChange={(value) => setTypeFilter(value || '')}
              options={typeFilterOptions.filter((o) => o.value)}
              style={{ width: 140 }}
            />
            <Select
              placeholder="Platform"
              allowClear
              value={platformFilter || undefined}
              onChange={(value) => setPlatformFilter(value || '')}
              options={platformFilterOptions.filter((o) => o.value)}
              style={{ width: 140 }}
            />
          </Space>

          <Table
            rowSelection={{
              selectedRowKeys,
              onChange: setSelectedRowKeys,
            }}
            columns={columns}
            dataSource={filteredImages}
            rowKey="id"
            loading={loading}
            onChange={handleTableChange}
            pagination={{
              pageSize,
              showSizeChanger: true,
              pageSizeOptions: ['10', '20', '50'],
              onShowSizeChange: handlePageSizeChange,
              showTotal: (total) => `${total} images`,
            }}
            expandable={{
              expandedRowRender,
              rowExpandable: (record) => record.regions.filter((r) => r.region).length > 1,
              expandedRowKeys,
              onExpandedRowsChange: (keys) => setExpandedRowKeys(keys as React.Key[]),
            }}
            locale={{
              emptyText: loading ? null : (
                <Space direction="vertical" align="center" style={{ padding: 24 }}>
                  <Text strong>No images</Text>
                  <Text type="secondary">No images to display.</Text>
                  <Button type="primary" onClick={() => setShowCreateModal(true)}>
                    Import Image
                  </Button>
                </Space>
              ),
            }}
          />
        </Card>
      </div>

      {/* Import Image Modal */}
      <Modal
        title="Import New Image"
        open={showCreateModal}
        onCancel={() => {
          setShowCreateModal(false);
          form.resetFields();
        }}
        onOk={handleCreateImage}
        confirmLoading={creating}
        okText="Import"
      >
        <Form form={form} layout="vertical">
          <Form.Item
            name="amiId"
            label="AMI ID"
            rules={[
              { required: true, message: 'Please enter an AMI ID' },
              {
                validator: (_, value) => {
                  if (!value || isValidAmiId(value)) {
                    return Promise.resolve();
                  }
                  return Promise.reject('Invalid AMI ID format. Must start with "ami-" followed by 8-17 hex characters.');
                },
              },
            ]}
            help="Enter the AWS AMI ID (e.g., ami-0123456789abcdef0)"
          >
            <Input placeholder="ami-0123456789abcdef0" />
          </Form.Item>
          <Form.Item name="name" label="Name" rules={[{ required: true, message: 'Please enter a name' }]}>
            <Input placeholder="Enter image name" />
          </Form.Item>
          <Form.Item name="platform" label="Platform" rules={[{ required: true, message: 'Please select a platform' }]}>
            <Select placeholder="Select platform" options={platformOptions} />
          </Form.Item>
          <Form.Item name="description" label="Description">
            <TextArea placeholder="Enter description (optional)" rows={3} />
          </Form.Item>
        </Form>
      </Modal>

      {/* Edit Image Modal */}
      <Modal
        title="Edit Image"
        open={showEditModal}
        onCancel={() => {
          setShowEditModal(false);
          setEditingImage(null);
        }}
        onOk={handleUpdateImage}
        okText="Update"
      >
        <Form form={editForm} layout="vertical">
          <Form.Item name="amiId" label="AMI ID">
            <Input disabled />
          </Form.Item>
          <Form.Item name="name" label="Name" rules={[{ required: true, message: 'Please enter a name' }]}>
            <Input placeholder="Enter image name" />
          </Form.Item>
          <Form.Item name="platform" label="Platform" rules={[{ required: true, message: 'Please select a platform' }]}>
            <Select placeholder="Select platform" options={platformOptions} />
          </Form.Item>
          <Form.Item name="description" label="Description">
            <TextArea placeholder="Enter description (optional)" rows={3} />
          </Form.Item>
        </Form>
      </Modal>

      {/* Delete Confirmation Modal */}
      <Modal
        title="Remove Images from Management"
        open={showDeleteModal}
        onCancel={() => setShowDeleteModal(false)}
        onOk={handleDeleteImages}
        confirmLoading={deleting}
        okText="Remove from Management"
      >
        <Alert
          type="info"
          message="This will only remove the images from Image Management. The actual AMI will remain in your AWS account and can be re-imported later."
          style={{ marginBottom: 16 }}
        />
        <div>
          <Text>Are you sure you want to remove the following {selectedImages.length} image(s) from management?</Text>
          <ul>
            {selectedImages.map((image) => (
              <li key={image.id}>
                {image.name} ({image.amiId || image.regions[0]?.amiId})
              </li>
            ))}
          </ul>
        </div>
      </Modal>

      {/* Copy to Region Modal */}
      <Modal
        title="Copy Image to Regions"
        open={showCopyModal}
        onCancel={() => {
          setShowCopyModal(false);
          setSelectedCopyRegions([]);
        }}
        onOk={handleCopyToRegions}
        confirmLoading={copying}
        okText="Copy Image"
        okButtonProps={{ disabled: selectedCopyRegions.length === 0 }}
      >
        <Alert
          type="info"
          message="Copying an AMI to another region creates a new AMI in the target region. This process may take several minutes depending on the image size."
          style={{ marginBottom: 16 }}
        />
        {selectedImages.length === 1 && (
          <div style={{ marginBottom: 16 }}>
            <Text strong>Image: </Text>
            <Text>{selectedImages[0].name}</Text>
            <br />
            <Text strong>Source Region: </Text>
            <Text>{selectedImages[0].region || selectedImages[0].regions[0]?.region || 'Unknown'}</Text>
            <br />
            <Text strong>Current Regions: </Text>
            <Text>
              {selectedImages[0].regions
                .map((r) => r.region)
                .filter(Boolean)
                .join(', ') || 'None'}
            </Text>
          </div>
        )}
        <Form.Item label="Target Regions" required>
          <Select
            mode="multiple"
            placeholder="Select regions to copy to"
            value={selectedCopyRegions}
            onChange={setSelectedCopyRegions}
            style={{ width: '100%' }}
            options={getAvailableCopyRegions().map((hub) => ({
              label: hub.isPrimary ? `${hub.region} (Primary)` : hub.region,
              value: hub.region,
            }))}
          />
        </Form.Item>
        {selectedCopyRegions.length > 0 && (
          <Text type="secondary">
            The image will be copied to {selectedCopyRegions.length} region(s). 
            New AMI IDs will be generated in each target region.
          </Text>
        )}
      </Modal>
    </AppLayoutAntd>
  );
};

export default ImageManagementAntd;
